In [ ]:
import requests # get post put patch APIS
client_id = ""
client_secret = ""

url = "https://api.ebay.com/identity/v1/oauth2/token"
data = {
    "grant_type": "client_credentials",
    "scope": "https://api.ebay.com/oauth/api_scope"
}

response= requests.post(url,
                       auth=(client_id,client_secret),
                       data=data)


token = response.json()["access_token"]
print(token)

v^1.1#i^1#p^1#r^0#I^3#f^0#t^H4sIAAAAAAAA/+VYfWwURRS/6xepUDSBUApq2gU0irc3u3tfu/YOr7Skh/TzSoUmBudm59qle7vLzp5tIcHaSAnGaICYCERDDOJHghEimPhBggpG1DQaDUqTogTURo0aEAgk6OxdKddKKNIzXuL9c5k3b9683++9N292QG9R8b39tf3nS5xT8nb2gt48p5ObCoqLChdOz8+bU+gAGQrOnb3zewv68n+sJDChGlIzJoauEVzenVA1IqWEQSZpapIOiUIkDSYwkSwkRcN1yySeBZJh6paOdJUpj1QHGQxFD0JcgAcAoYAsUql2xWaLHmSQBws+n8jF+LjAQT5G5wlJ4ohGLKhZQYYHvM8FBBcItPCcBASJ97A+TmxjyluxSRRdoyosYEIpd6XUWjPD1+u7CgnBpkWNMKFIeEm0IRyprqlvqXRn2AqN8BC1oJUkY0eLdRmXt0I1ia+/DUlpS9EkQpgQxh1K7zDWqBS+4sxNuJ+iWvbI/hjiAzzGfj8EnqxQuUQ3E9C6vh+2RJFd8ZSqhDVLsXomYpSyEVuNkTUyqqcmItXl9l9TEqpKXMFmkKmpCq8MNzYyoaVQgw92QNVVg/REApvI1dhc7cIeLHsA9ssuXvQFPD6vPLJR2toIzeN2WqxrsmKTRsrrdasKU6/xWG6A5M3ghio1aA1mOG7ZHmXqCaMccm12UNNRTFodmh1XnKBElKeGE0dgdLVlmUosaeFRC+MnUhQFGWgYisyMn0zl4kj6dJMg02FZhuR2d3V1sV0Cq5vtblqGnHtF3bIo6sAJyFBdu9bT+srEC1xKCgrCdCVRJKvHoL5001ylDmjtTMjrFb0gMML7WLdC46V/E2Rgdo+tiGxVCCeIcsCHvFCMQ87r5bNRIaGRJHXbfuAY7HEloNmJLUOFCLsQzbMkTVhFlgRvnBcCceySfWLc5RHjcVfMK/tcXBxjgHEshsTA/6lQbjTVoxiZ2MpKrmctz9tRuxHVsJushhoRZE+3XxMFdU2dtzW8hoecqC/3G/W1cqvKo+CNVsM1wS9WFcpMC90/GwTYtZ49Emp1YmF5UvCiSDdwo64qqCe3AiyYciM0rZ4oVlUqmBTIsGFEsnNWZw3ePzwmbg539nrUf9SfromK2CmbW6js9YQagIbC2h2IpUF127WuQ3r9sMWrUl5PCrdCb645hZqCTKNV5PSVk03BZcmjiDUx0ZMmvW2zDfYNrEXvxBrtZ5apqyo2W7lJ13MikbRgTMW5VthZSHAF5liz5fx+AQAhADyTwoVSrXRVrh1J2TiKC/qcFRPib8ZQTeQWdsPU5SSy75j/wieDe+wDRsiR+nF9zvdBn/NgntMJKsECbh6oKMpfXpA/bQ5RLMwqMM4SpV2j3+UmZjtxjwEVM2+G4+hX39Tf+c7SVzadKu3dMN+9xTE94/1k58Ng9ugLSnE+NzXjOQXcfnWmkLu1tIT3AQEEeA4IvKcNzLs6W8DNKpjJD4cOc54HXty6f9fj/Zr77OclTStAyaiS01nooMF25A081Pt2cOCQUnjizKyNc78+fEr86MyWFd+JM/eWkdpP/bv3Fw9vG9qx7fjlOZd+C8169uTeZZUNyq7b5j+5vO2Plwdf3fd9c2Sl/vMLC7avaxr6aWjzZ58cKT58V9PQE8VHF03r3Ns1e9VR/shLmx775feqirlTjvVFahoqyk4W3fPMwtMHmNLzwzvkPevXnZvh37f2qeeqSs+cLvn27Jv9kZltbyxF7rcGy/Yc3yx8cd/Bi1/uRk+x2pFk97nu995d+MgtLRvX3n9offWBprvLNvCDA61drwtAjN0R3f7rn6zjw2PH5y05tvHc1td+mPFx2Y7zZRculz7/9PCuulj/iUuLPqhxGI6Bi7XNc7svHBpMx/IvpNnbJdkSAAA=

In [2]:

import pandas as pd
search_url = "https://api.ebay.com/buy/browse/v1/item_summary/search"
y =input("Enter the theme for your product:")
x=int(input("How many items do you want to fetch?"))

all_items=[]
limit=50
total_needed=x

for offset in range(0, total_needed, 50):
    response = requests.get(
        "https://api.ebay.com/buy/browse/v1/item_summary/search",
        params={
            "q": y,
            "limit": 50,
            "offset": offset
        },
        headers={
            "Authorization": f"Bearer {token}"
        }
    )
    data = response.json()
    all_items.extend(data.get('itemSummaries', []))


df=pd.DataFrame(all_items)
df

,itemId,title,itemGroupHref,leafCategoryIds,categories,image,price,itemGroupType,itemHref,seller,...,itemCreationDate,topRatedBuyingExperience,priorityListing,listingMarketplaceId,epid,priceDisplayCondition,pickupOptions,bidCount,currentBidPrice,itemEndDate
0,v1|286393092388|588498748794,Dell Latitude Laptop Computer PC Intel i5 Up T...,https://api.ebay.com/buy/browse/v1/item/get_it...,[177],"[{'categoryId': '177', 'categoryName': 'PC Lap...",{'imageUrl': 'https://i.ebayimg.com/images/g/P...,"{'value': '303.73', 'currency': 'USD'}",SELLER_DEFINED_VARIATIONS,https://api.ebay.com/buy/browse/v1/item/v1%7C2...,"{'username': 'discountcomputerdepot', 'feedbac...",...,2025-03-08T15:50:37.000Z,False,False,EBAY_US,NaN,NaN,NaN,NaN,NaN,NaN
1,v1|177800317663|0,"Dell Latitude 5289 2-in-1 12.3"" i5-7600U@2.8GH...",NaN,[177],"[{'categoryId': '177', 'categoryName': 'PC Lap...",{'imageUrl': 'https://i.ebayimg.com/images/g/U...,"{'value': '159.99', 'currency': 'USD'}",NaN,https://api.ebay.com/buy/browse/v1/item/v1%7C1...,"{'username': 'boxdealsco', 'feedbackPercentage...",...,2026-01-23T04:59:35.000Z,False,True,EBAY_US,NaN,NaN,NaN,NaN,NaN,NaN
2,v1|256879744174|557422176898,Dell Latitude 15.6” FHD Core i5 Laptop PC Up T...,https://api.ebay.com/buy/browse/v1/item/get_it...,[177],"[{'categoryId': '177', 'categoryName': 'PC Lap...",{'imageUrl': 'https://i.ebayimg.com/images/g/k...,"{'value': '301.20', 'currency': 'USD'}",SELLER_DEFINED_VARIATIONS,https://api.ebay.com/buy/browse/v1/item/v1%7C2...,"{'username': 'discountcomputerdepot', 'feedbac...",...,2025-04-02T14:32:55.000Z,False,True,EBAY_US,NaN,NaN,NaN,NaN,NaN,NaN
3,v1|167783058564|0,"HP X360 G2 EE 11"" Laptop Windows 11 Pro Touch ...",NaN,[177],"[{'categoryId': '177', 'categoryName': 'PC Lap...",{'imageUrl': 'https://i.ebayimg.com/images/g/9...,"{'value': '85.00', 'currency': 'USD'}",NaN,https://api.ebay.com/buy/browse/v1/item/v1%7C1...,"{'username': 'yuansheng', 'feedbackPercentage'...",...,2025-09-10T22:56:41.000Z,False,True,EBAY_US,NaN,NaN,NaN,NaN,NaN,NaN
4,v1|276709583737|0,"Acer Swift Go 14"" Laptop Intel Core Ultra 7 15...",NaN,[177],"[{'categoryId': '177', 'categoryName': 'PC Lap...",{'imageUrl': 'https://i.ebayimg.com/images/g/m...,"{'value': '371.99', 'currency': 'USD'}",NaN,https://api.ebay.com/buy/browse/v1/item/v1%7C2...,"{'username': 'acer', 'feedbackPercentage': '98...",...,2024-10-30T23:21:59.000Z,False,False,EBAY_US,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,v1|126758706961|0,DELL LATITUDE 3480 INTEL CORE I5-7200U 2.50GHZ...,NaN,[177],"[{'categoryId': '177', 'categoryName': 'PC Lap...",{'imageUrl': 'https://i.ebayimg.com/images/g/Y...,"{'value': '83.97', 'currency': 'USD'}",NaN,https://api.ebay.com/buy/browse/v1/item/v1%7C1...,"{'username': 'tvrsales3', 'feedbackPercentage'...",...,2024-11-04T10:30:21.000Z,False,False,EBAY_US,NaN,NaN,NaN,NaN,NaN,NaN
4996,v1|325880847972|0,HO Chromebook 11 Inch,NaN,[177],"[{'categoryId': '177', 'categoryName': 'PC Lap...",{'imageUrl': 'https://i.ebayimg.com/images/g/V...,"{'value': '100.00', 'currency': 'USD'}",NaN,https://api.ebay.com/buy/browse/v1/item/v1%7C3...,"{'username': '509parts', 'feedbackPercentage':...",...,2023-11-09T22:20:11.000Z,False,False,EBAY_US,NaN,NaN,NaN,NaN,NaN,NaN
4997,v1|335267242364|0,Dell Bistro 1500 Model PP22L Laptop Works! Inc...,NaN,[177],"[{'categoryId': '177', 'categoryName': 'PC Lap...",{'imageUrl': 'https://i.ebayimg.com/images/g/B...,"{'value': '49.99', 'currency': 'USD'}",NaN,https://api.ebay.com/buy/browse/v1/item/v1%7C3...,"{'username': 'barbstar1954', 'feedbackPercenta...",...,2024-02-20T15:47:28.000Z,False,False,EBAY_US,NaN,NaN,[{'pickupLocationType': 'ARRANGED_LOCATION'}],NaN,NaN,NaN
4998,v1|388603532539|0,HP 15.6 In HD Touch-screen Intel I3 8gb Ram 12...,NaN,[177],"[{'categoryId': '177', 'categoryName': 'PC Lap...",{'imageUrl': 'https://i.ebayimg.com/images/g/e...,"{'value': '359.00', 'currency': 'USD'}",NaN,https://api.ebay.com/buy/browse/v1/item/v1%7C3...,"{'username': 'te-62331', 'feedbackPercentage':...",...,2025-06-18T18:51:25.000Z,False,True,EBAY_US,NaN,NaN,NaN,NaN,NaN,NaN
4999,v1|276881140042|0,"Lenovo V14-IIL 14"" Laptop i3-1005G1@1.2GHz 8GB...",NaN,[177],"[{'categoryId': '177', 'categoryName': 'PC Lap...",{'imageUrl': 'https://i.ebayimg.com/images/g/2...,"{'value': '130.00', 'currency': 'USD'}",NaN,https://api.ebay.com/buy/browse/v1/item/v1%7C2...,"{'username': 'juluplus', 'feedbackPercentage':...",...,2025-02-18T21:45:00.000Z,False,True,EBAY_US,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
import requests
import pandas as pd
itms = []

while True:
    z = input("Do you want to add a theme? (Y/N):").upper()
    if z != "Y":
        break
    
    p = input("Enter the theme for your product:")
    q = int(input("How many items do you want to fetch?"))
    
    
    limit = 50
    for offset in range(0, q, limit):
        response = requests.get(
            "https://api.ebay.com/buy/browse/v1/item_summary/search",
            params={
                "q": p,
                "limit": limit,
                "offset": offset
            },
            headers={
                "Authorization": f"Bearer {token}"
            }
        )
        data = response.json()
        itms.extend(data.get('itemSummaries', []))

print(f"Total items fetched: {len(itms)}")
df1=pd.DataFrame(itms)
df_all=pd.concat([df,df1],ignore_index=True)
if len(itms)==0:
    df_all=df

Total items fetched: 7100

In [4]:
df_all

,itemId,title,itemGroupHref,leafCategoryIds,categories,image,price,itemGroupType,itemHref,seller,...,itemCreationDate,topRatedBuyingExperience,priorityListing,listingMarketplaceId,epid,priceDisplayCondition,pickupOptions,bidCount,currentBidPrice,itemEndDate
0,v1|286393092388|588498748794,Dell Latitude Laptop Computer PC Intel i5 Up T...,https://api.ebay.com/buy/browse/v1/item/get_it...,[177],"[{'categoryId': '177', 'categoryName': 'PC Lap...",{'imageUrl': 'https://i.ebayimg.com/images/g/P...,"{'value': '303.73', 'currency': 'USD'}",SELLER_DEFINED_VARIATIONS,https://api.ebay.com/buy/browse/v1/item/v1%7C2...,"{'username': 'discountcomputerdepot', 'feedbac...",...,2025-03-08T15:50:37.000Z,False,False,EBAY_US,NaN,NaN,NaN,NaN,NaN,NaN
1,v1|177800317663|0,"Dell Latitude 5289 2-in-1 12.3"" i5-7600U@2.8GH...",NaN,[177],"[{'categoryId': '177', 'categoryName': 'PC Lap...",{'imageUrl': 'https://i.ebayimg.com/images/g/U...,"{'value': '159.99', 'currency': 'USD'}",NaN,https://api.ebay.com/buy/browse/v1/item/v1%7C1...,"{'username': 'boxdealsco', 'feedbackPercentage...",...,2026-01-23T04:59:35.000Z,False,True,EBAY_US,NaN,NaN,NaN,NaN,NaN,NaN
2,v1|256879744174|557422176898,Dell Latitude 15.6” FHD Core i5 Laptop PC Up T...,https://api.ebay.com/buy/browse/v1/item/get_it...,[177],"[{'categoryId': '177', 'categoryName': 'PC Lap...",{'imageUrl': 'https://i.ebayimg.com/images/g/k...,"{'value': '301.20', 'currency': 'USD'}",SELLER_DEFINED_VARIATIONS,https://api.ebay.com/buy/browse/v1/item/v1%7C2...,"{'username': 'discountcomputerdepot', 'feedbac...",...,2025-04-02T14:32:55.000Z,False,True,EBAY_US,NaN,NaN,NaN,NaN,NaN,NaN
3,v1|167783058564|0,"HP X360 G2 EE 11"" Laptop Windows 11 Pro Touch ...",NaN,[177],"[{'categoryId': '177', 'categoryName': 'PC Lap...",{'imageUrl': 'https://i.ebayimg.com/images/g/9...,"{'value': '85.00', 'currency': 'USD'}",NaN,https://api.ebay.com/buy/browse/v1/item/v1%7C1...,"{'username': 'yuansheng', 'feedbackPercentage'...",...,2025-09-10T22:56:41.000Z,False,True,EBAY_US,NaN,NaN,NaN,NaN,NaN,NaN
4,v1|276709583737|0,"Acer Swift Go 14"" Laptop Intel Core Ultra 7 15...",NaN,[177],"[{'categoryId': '177', 'categoryName': 'PC Lap...",{'imageUrl': 'https://i.ebayimg.com/images/g/m...,"{'value': '371.99', 'currency': 'USD'}",NaN,https://api.ebay.com/buy/browse/v1/item/v1%7C2...,"{'username': 'acer', 'feedbackPercentage': '98...",...,2024-10-30T23:21:59.000Z,False,False,EBAY_US,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12095,v1|389316686930|656629817254,"Apple iPhone 8 - Mint Condition, 64GB/128GB/25...",https://api.ebay.com/buy/browse/v1/item/get_it...,[9355],"[{'categoryId': '9355', 'categoryName': 'Cell ...",{'imageUrl': 'https://i.ebayimg.com/images/g/3...,"{'value': '119.00', 'currency': 'USD'}",SELLER_DEFINED_VARIATIONS,https://api.ebay.com/buy/browse/v1/item/v1%7C3...,"{'username': 'sarahcell', 'feedbackPercentage'...",...,2025-12-01T14:55:50.000Z,False,False,EBAY_US,239054260,NaN,NaN,NaN,NaN,NaN
12096,v1|388976680228|0,Apple iPhone 13 - 128 GB - Starlight (Unlocked),NaN,[9355],"[{'categoryId': '9355', 'categoryName': 'Cell ...",{'imageUrl': 'https://i.ebayimg.com/images/g/F...,"{'value': '500.00', 'currency': 'USD'}",NaN,https://api.ebay.com/buy/browse/v1/item/v1%7C3...,"{'username': 'ice-3699', 'feedbackPercentage':...",...,2025-09-16T19:43:18.000Z,False,False,EBAY_US,8049288614,NaN,[{'pickupLocationType': 'ARRANGED_LOCATION'}],NaN,NaN,NaN
12097,v1|137103691849|0,"iPhone 17 Pro Max Case Smooth Crystal Clear, A...",NaN,[9355],"[{'categoryId': '9355', 'categoryName': 'Cell ...",{'imageUrl': 'https://i.ebayimg.com/images/g/Y...,"{'value': '38.51', 'currency': 'USD'}",NaN,https://api.ebay.com/buy/browse/v1/item/v1%7C1...,"{'username': 'sdbro-0', 'feedbackPercentage': ...",...,2026-03-08T14:31:00.000Z,False,False,EBAY_US,NaN,NaN,NaN,NaN,NaN,NaN
12098,v1|388200000001|655387538578,"Apple iPhone XS 64GB/256GB - Space Gray, Silve...",https://api.ebay.com/buy/browse/v1/item/get_it...,[9355],"[{'categoryId': '9355', 'categoryName': 'Cell ...",{'imageUrl': 'https://i.ebayimg.com/images/g/k...,"{'value': '184.00', 'currency': 'USD'}",SELLER_DEFINED_VARIATIONS,https://api.ebay.com/buy/browse/v1/item/v1%7C3...,"{'username': 'houstoncellphones', 'feedbackPer...",...,2025-04-04T16:45:19.000Z,True,True,EBAY_US,27023700684,NaN,NaN,NaN,NaN,NaN
12099,v1|285595308985|0,Apple iPhone 13 - 128GB - Pink (AT&T) Excellen...,NaN,[9355],"[{'categoryId': '9355', 'categoryName': 'Cell ...",{'imageUrl': 'https://i.ebayimg.com/images/g/7...,"{'value': '489.00', 'currency': 'USD'}",NaN,https://api.ebay.com/buy/browse/v1/item/v1%7C2...,"{'username': 'fast-connect', 'feedbackPercenta...",...,2023-12-06T21:23:49.000Z,True,True,EBAY_US,28049285693,NaN,NaN,NaN,NaN,NaN

In [5]:
df_all.to_csv(r'C:\Users\Ahmed\Desktop\eBay_UNCleaned.csv')

In [ ]:
# process of data cleaning (sliver)
df_updated1=df_all.rename(columns={'itemId':'ProductId'})
df_updated2=df_updated1.rename(columns={'title': 'Product'})
df_updated3=df_updated2.rename(columns={'leafCategoryIds':'CategoryId'})
df_updated4=df_updated3.rename(columns={'itemWebUrl':'productWebUrl'})
df_updated5=df_updated4.rename(columns={'legacyItemId':'legacyProductId'})
df_updated6=df_updated5.rename(columns={'itemOriginDate':'productOriginDate'})
df_updated=df_updated6.rename(columns={'itemCreationDate':'productCreationDate'})
#itemOriginDate
df_updated


df_updated['productOriginDate']= pd.to_datetime(df_updated['productOriginDate'])
df_updated['productCreationDate']= pd.to_datetime(df_updated['productCreationDate'])






x = []
cu = []

for i in df_updated['price']:
    if isinstance(i, dict):
        x.append(float(i.get('value', 0)))
        cu.append(i.get('currency', 'Unknown'))
    else:
        x.append(float(i))
        cu.append('Unknown')


df_updated['price']=x
df_updated['currency']=cu
df_updated=df_updated.drop('itemGroupHref',axis=1)
df_updated=df_updated.drop('itemHref',axis=1)
df_updated=df_updated.drop('itemGroupType',axis=1)
df_updated=df_updated.drop('additionalImages',axis=1)
df_updated


df_updated['marketingPrice'] = df_updated['marketingPrice'].fillna("Unknown")
df_updated['pickupOptions']=df_updated['pickupOptions'].fillna("Unknown")
df_updated['epid']=df_updated['epid'].fillna("Unknown")
df_updated['priceDisplayCondition']=df_updated['priceDisplayCondition'].fillna("Unknown")
if 'bidCount' in df_updated.columns and 'currentBidPrice' in df_updated.columns and 'itemEndDate' in df_updated.columns:
    df_updated['bidCount'] = df_updated['bidCount'].fillna("Unknown")
    df_updated['currentBidPrice'] = df_updated['currentBidPrice'].fillna("Unknown")
    df_updated['itemEndDate']=df_updated['itemEndDate'].fillna("Unknown")
df_updated['image']=df_updated['image'].fillna("Unknown")
df_updated['categories']=df_updated['categories'].fillna("Unknown")
df_updated['condition']=df_updated['condition'].fillna("Unknown")
df_updated['shippingOptions']=df_updated['shippingOptions'].fillna("Unknown")
z=[]
m=[]
for i in df_updated['image']:
   if 'imageUrl' in i:
      m.append(i['imageUrl'])
   else:
      m.append("Unknown")
      


df_updated['image']=m
df_updated=df_updated.drop('thumbnailImages',axis=1)
a=[]

#for i in df_updated['categories']:
 #  b=i[0]
  # a.append(b['categoryName'])

#df_updated['categories']=a
#df_updated


s=[]
sc1=[]
for i in df_updated['shippingOptions']:
   sc=i[0]
  
   if 'shippingCostType' in sc:
      s.append(sc['shippingCostType'].title())
   else:
      s.append('Unknown')
   

df_updated['shippingCostType']=s
for i in df_updated['shippingOptions']:
   sc=i[0]
   if 'shippingCost' in sc:
      if sc['shippingCost']['value']=='0.00':
         sc1.append(0.00)
      elif sc['shippingCost']['value']!='0.00':
         sc1.append(f'{float(sc['shippingCost']['value'])}')
   else:
      sc1.append(0.00)

sc2=[]
for i in df_updated['shippingOptions']:
   sc=i[0]
   if 'minEstimatedDeliveryDate' in sc:
      sc2.append(pd.to_datetime(sc['minEstimatedDeliveryDate']))
   else:
      sc2.append(0-0-0)

sc3=[]
for i in df_updated['shippingOptions']:
   sc=i[0]
   if 'maxEstimatedDeliveryDate' in sc:
      sc3.append(pd.to_datetime(sc['maxEstimatedDeliveryDate']))
   else:
      sc3.append(0-0-0)

co=[]
for i in df_updated['itemLocation']:
   if 'country' in i:
      co.append(i['country'])
   else:
      co.append("Unknown")

pc=[]
for i in df_updated['itemLocation']:
   if 'postalCode' in i:
      pc.append(i['postalCode'])
   else:
      pc.append("Unknown")

fx=[]
for i in df_updated['buyingOptions']:
   if len(i) == 2:
      fx.append("Fixed Price and Best Offer")
   else:
      fx.append("Fixed Price")

pk=[]
for i in df_updated['pickupOptions']:
   d=i[0]
   if 'pickupLocationType' in i[0]:
      pk.append(d['pickupLocationType'].title())
   else:
      pk.append("Unknown")

ori=[]
for i in df_updated['marketingPrice']:
  if 'originalPrice' in i:
     ori.append(float(i['originalPrice']['value']))
  else:
     ori.append(0.00)

disp=[]
for i in df_updated['marketingPrice']:
  if 'discountPercentage' in i:
     disp.append(int(i['discountPercentage']))
  else:
     disp.append(0)


disa=[]
for i in df_updated['marketingPrice']:
  if 'discountAmount' in i:
     disa.append(float(i['discountAmount']['value']))
  else:
     disa.append(0.00)

df_updated['originalPrice']=ori
df_updated['discountPercentage']=disp
df_updated['discountAmount']=disa



cat=[]
idc=[]
for i in df_updated['categories']:
   b=i[0]
   cat.append(b['categoryName'])



for i in df_updated['CategoryId']:
   idc.append(int(i[0]))

df_updated['CategoryId']=idc

df_updated['categories']=cat
df_updated['shippingCost']=sc1
df_updated['minEstimatedDeliveryDate']=sc2
df_updated['maxEstimatedDeliveryDate']=sc3
df_updated['Country']=co
df_updated['PostalCode']=pc
df_updated['buyingOptions']=fx
df_updated['pickupOptions']=pk
df_updated=df_updated.drop('shippingOptions',axis=1)
df_updated=df_updated.drop('itemLocation',axis=1)
df_updated=df_updated.drop('marketingPrice',axis=1)
df_updated=df_updated.drop('legacyProductId',axis=1)
df_updated=df_updated.drop('priorityListing',axis=1)
if 'bidCount' in df_updated.columns:
   df_updated=df_updated.drop('bidCount',axis=1)
df_updated=df_updated.drop('epid',axis=1)


se=[]
fp=[]
fs=[]
for i in df_updated['seller']:
   if 'username' in i:
      se.append(i['username'])
   else:
      se.append('Unknown User')
   

for i in df_updated['seller']:
   if 'feedbackPercentage' in i:
      fp.append(float(i['feedbackPercentage']))
   else:
      fp.append(0.0)

for i in df_updated['seller']:
   if 'feedbackScore' in i:
      fs.append(int(i['feedbackScore']))
   else:
      fs.append(0)

df_updated['seller']=se
df_updated['feedbackPrecentage']=fp
df_updated['feedbackScore']=fs

df_updated['ProductId'] = df_updated['ProductId'].str.split('|').str[1]
df_updated['ProductId'] = df_updated['ProductId'].astype(int)
df_updated
cb=[]
if 'currentBidPrice' in df_updated.columns:
   for i in df_updated['currentBidPrice']:
    if 'value' in i:
     cb.append(float(i['value']))
    elif 'Unknown'in i:
      cb.append(0)

if 'currentBidPrice' in df_updated.columns:
   df_updated['currentBidPrice']=cb

if 'itemEndDate' in df_updated.columns:
   df_updated=df_updated.drop('itemEndDate',axis=1)

In [ ]:
df_updated['conditionId']=df_updated['conditionId'].fillna(404)

In [ ]:
df_updated.to_csv(r'C:\Users\Ahmed\Desktop\eBay_Cleaned.csv')

In [33]:
df_updated

,ProductId,Product,CategoryId,categories,image,price,seller,condition,conditionId,buyingOptions,...,originalPrice,discountPercentage,discountAmount,shippingCost,minEstimatedDeliveryDate,maxEstimatedDeliveryDate,Country,PostalCode,feedbackPrecentage,feedbackScore
0,286393092388,Dell Latitude Laptop Computer PC Intel i5 Up T...,177,PC Laptops & Netbooks,https://i.ebayimg.com/images/g/PcAAAeSwFd1plzs...,303.73,discountcomputerdepot,Good - Refurbished,2030,Fixed Price,...,337.48,10,33.75,0.0,2026-03-11 07:00:00+00:00,2026-03-13 07:00:00+00:00,US,757**,99.3,154068
1,177800317663,"Dell Latitude 5289 2-in-1 12.3"" i5-7600U@2.8GH...",177,PC Laptops & Netbooks,https://i.ebayimg.com/images/g/UmAAAeSwhPZpcvz...,159.99,boxdealsco,Used,3000,Fixed Price and Best Offer,...,0.00,0,0.00,0.0,2026-03-12 07:00:00+00:00,2026-03-18 07:00:00+00:00,US,554**,100.0,603
2,256879744174,Dell Latitude 15.6” FHD Core i5 Laptop PC Up T...,177,PC Laptops & Netbooks,https://i.ebayimg.com/images/g/kSsAAeSw0r5pZ8W...,301.2,discountcomputerdepot,Good - Refurbished,2030,Fixed Price,...,334.67,10,33.47,0.0,2026-03-11 07:00:00+00:00,2026-03-13 07:00:00+00:00,US,757**,99.3,154068
3,167783058564,"HP X360 G2 EE 11"" Laptop Windows 11 Pro Touch ...",177,PC Laptops & Netbooks,https://i.ebayimg.com/images/g/9rwAAeSwuU5owf~...,85.0,yuansheng,Used,3000,Fixed Price and Best Offer,...,0.00,0,0.00,0.0,2026-03-11 07:00:00+00:00,2026-03-13 07:00:00+00:00,US,917**,97.8,2340
4,276709583737,"Acer Swift Go 14"" Laptop Intel Core Ultra 7 15...",177,PC Laptops & Netbooks,https://i.ebayimg.com/images/g/m3YAAeSwJJZpOyM...,371.99,acer,Certified - Refurbished,2000,Fixed Price,...,799.99,54,428.00,0.0,2026-03-11 07:00:00+00:00,2026-03-13 07:00:00+00:00,US,785**,98.9,110846
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12095,389316686930,"Apple iPhone 8 - Mint Condition, 64GB/128GB/25...",9355,Cell Phones & Smartphones,https://i.ebayimg.com/images/g/3HkAAeSwgyhpLau...,119.0,sarahcell,Used,3000,Fixed Price,...,0.00,0,0.00,0.0,2026-03-10 07:00:00+00:00,2026-03-11 07:00:00+00:00,US,770**,99.6,5391
12096,388976680228,Apple iPhone 13 - 128 GB - Starlight (Unlocked),9355,Cell Phones & Smartphones,https://i.ebayimg.com/images/g/FBYAAeSw~MVoyby...,500.0,ice-3699,Used,3000,Fixed Price and Best Offer,...,0.00,0,0.00,0.0,0,0,US,460**,0.0,1
12097,137103691849,"iPhone 17 Pro Max Case Smooth Crystal Clear, A...",9355,Cell Phones & Smartphones,https://i.ebayimg.com/images/g/YekAAeSwXJ1prA~...,38.51,sdbro-0,New,1000,Fixed Price,...,0.00,0,0.00,0.0,2026-03-11 07:00:00+00:00,2026-03-14 07:00:00+00:00,US,Unknown,100.0,5
12098,388200000001,"Apple iPhone XS 64GB/256GB - Space Gray, Silve...",9355,Cell Phones & Smartphones,https://i.ebayimg.com/images/g/kWMAAOSwieln8Av...,184.0,houstoncellphones,Used,3000,Fixed Price,...,0.00,0,0.00,0.0,2026-03-10 07:00:00+00:00,2026-03-11 07:00:00+00:00,US,770**,99.9,1574
12099,285595308985,Apple iPhone 13 - 128GB - Pink (AT&T) Excellen...,9355,Cell Phones & Smartphones,https://i.ebayimg.com/images/g/7wYAAOSwWfplcOX...,489.0,fast-connect,Used,3000,Fixed Price,...,0.00,0,0.00,0.0,0,0,US,331**,98.0,2481

In [1]:
import pandas as pd
df_updated=pd.read_csv(r'C:\Users\Ahmed\Desktop\eBay_Cleaned.csv')
df_updated = df_updated.drop(columns=['Unnamed: 0'])

In [2]:
df_updated

,ProductId,Product,CategoryId,categories,image,price,seller,condition,conditionId,buyingOptions,...,originalPrice,discountPercentage,discountAmount,shippingCost,minEstimatedDeliveryDate,maxEstimatedDeliveryDate,Country,PostalCode,feedbackPrecentage,feedbackScore
0,286393092388,Dell Latitude Laptop Computer PC Intel i5 Up T...,177,PC Laptops & Netbooks,https://i.ebayimg.com/images/g/PcAAAeSwFd1plzs...,303.73,discountcomputerdepot,Good - Refurbished,2030,Fixed Price,...,337.48,10,33.75,0.0,2026-03-11 07:00:00+00:00,2026-03-13 07:00:00+00:00,US,757**,99.3,154068
1,177800317663,"Dell Latitude 5289 2-in-1 12.3"" i5-7600U@2.8GH...",177,PC Laptops & Netbooks,https://i.ebayimg.com/images/g/UmAAAeSwhPZpcvz...,159.99,boxdealsco,Used,3000,Fixed Price and Best Offer,...,0.00,0,0.00,0.0,2026-03-12 07:00:00+00:00,2026-03-18 07:00:00+00:00,US,554**,100.0,603
2,256879744174,Dell Latitude 15.6” FHD Core i5 Laptop PC Up T...,177,PC Laptops & Netbooks,https://i.ebayimg.com/images/g/kSsAAeSw0r5pZ8W...,301.20,discountcomputerdepot,Good - Refurbished,2030,Fixed Price,...,334.67,10,33.47,0.0,2026-03-11 07:00:00+00:00,2026-03-13 07:00:00+00:00,US,757**,99.3,154068
3,167783058564,"HP X360 G2 EE 11"" Laptop Windows 11 Pro Touch ...",177,PC Laptops & Netbooks,https://i.ebayimg.com/images/g/9rwAAeSwuU5owf~...,85.00,yuansheng,Used,3000,Fixed Price and Best Offer,...,0.00,0,0.00,0.0,2026-03-11 07:00:00+00:00,2026-03-13 07:00:00+00:00,US,917**,97.8,2340
4,276709583737,"Acer Swift Go 14"" Laptop Intel Core Ultra 7 15...",177,PC Laptops & Netbooks,https://i.ebayimg.com/images/g/m3YAAeSwJJZpOyM...,371.99,acer,Certified - Refurbished,2000,Fixed Price,...,799.99,54,428.00,0.0,2026-03-11 07:00:00+00:00,2026-03-13 07:00:00+00:00,US,785**,98.9,110846
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10587,176485105171,Apple iPhone 8 A1905 Orange Only 256GB Silver B,9355,Cell Phones & Smartphones,https://i.ebayimg.com/images/g/pNQAAOSwTJhmnw1...,139.99,yywirelesss,Used,3000,Fixed Price,...,114.00,-23,-25.99,0.0,2026-03-11 07:00:00+00:00,2026-03-12 07:00:00+00:00,US,Unknown,99.5,181920
10588,354363592098,Apple iPhone 12 mini - 64GB - White (AT&T),9355,Cell Phones & Smartphones,https://i.ebayimg.com/images/g/3fkAAOSwlWBjVL~...,299.99,cruss-42,Used,3000,Fixed Price and Best Offer,...,0.00,0,0.00,0.0,2026-03-12 07:00:00+00:00,2026-03-18 07:00:00+00:00,US,334**,100.0,20
10589,137103691849,"iPhone 17 Pro Max Case Smooth Crystal Clear, A...",9355,Cell Phones & Smartphones,https://i.ebayimg.com/images/g/YekAAeSwXJ1prA~...,38.51,sdbro-0,New,1000,Fixed Price,...,0.00,0,0.00,0.0,2026-03-11 07:00:00+00:00,2026-03-14 07:00:00+00:00,US,Unknown,100.0,5
10590,388200000001,"Apple iPhone XS 64GB/256GB - Space Gray, Silve...",9355,Cell Phones & Smartphones,https://i.ebayimg.com/images/g/kWMAAOSwieln8Av...,184.00,houstoncellphones,Used,3000,Fixed Price,...,0.00,0,0.00,0.0,2026-03-10 07:00:00+00:00,2026-03-11 07:00:00+00:00,US,770**,99.9,1574
10591,285595308985,Apple iPhone 13 - 128GB - Pink (AT&T) Excellen...,9355,Cell Phones & Smartphones,https://i.ebayimg.com/images/g/7wYAAOSwWfplcOX...,489.00,fast-connect,Used,3000,Fixed Price,...,0.00,0,0.00,0.0,0,0,US,331**,98.0,2481

In [325]:
Product_Dim=df_updated.loc[:,['ProductId','Product','image','adultOnly','buyingOptions','availableCoupons','productWebUrl']]
Product_Dim.to_csv(r'C:\Users\Ahmed\Desktop\DimProduct.csv')
Product_Dim

,ProductId,Product,image,adultOnly,buyingOptions,availableCoupons,productWebUrl
0,286393092388,Dell Latitude Laptop Computer PC Intel i5 Up T...,https://i.ebayimg.com/images/g/PcAAAeSwFd1plzs...,False,Fixed Price,False,https://www.ebay.com/itm/286393092388?_skw=Lap...
1,177800317663,"Dell Latitude 5289 2-in-1 12.3"" i5-7600U@2.8GH...",https://i.ebayimg.com/images/g/UmAAAeSwhPZpcvz...,False,Fixed Price and Best Offer,False,https://www.ebay.com/itm/177800317663?_skw=Lap...
2,256879744174,Dell Latitude 15.6” FHD Core i5 Laptop PC Up T...,https://i.ebayimg.com/images/g/kSsAAeSw0r5pZ8W...,False,Fixed Price,False,https://www.ebay.com/itm/256879744174?_skw=Lap...
3,167783058564,"HP X360 G2 EE 11"" Laptop Windows 11 Pro Touch ...",https://i.ebayimg.com/images/g/9rwAAeSwuU5owf~...,False,Fixed Price and Best Offer,False,https://www.ebay.com/itm/167783058564?_skw=Lap...
4,276709583737,"Acer Swift Go 14"" Laptop Intel Core Ultra 7 15...",https://i.ebayimg.com/images/g/m3YAAeSwJJZpOyM...,False,Fixed Price,False,https://www.ebay.com/itm/276709583737?_skw=Lap...
...,...,...,...,...,...,...,...
12088,176485105171,Apple iPhone 8 A1905 Orange Only 256GB Silver B,https://i.ebayimg.com/images/g/pNQAAOSwTJhmnw1...,False,Fixed Price,False,https://www.ebay.com/itm/176485105171?_skw=iPh...
12089,354363592098,Apple iPhone 12 mini - 64GB - White (AT&T),https://i.ebayimg.com/images/g/3fkAAOSwlWBjVL~...,False,Fixed Price and Best Offer,False,https://www.ebay.com/itm/354363592098?_skw=iPh...
12097,137103691849,"iPhone 17 Pro Max Case Smooth Crystal Clear, A...",https://i.ebayimg.com/images/g/YekAAeSwXJ1prA~...,False,Fixed Price,False,https://www.ebay.com/itm/137103691849?_skw=iPh...
12098,388200000001,"Apple iPhone XS 64GB/256GB - Space Gray, Silve...",https://i.ebayimg.com/images/g/kWMAAOSwieln8Av...,False,Fixed Price,False,https://www.ebay.com/itm/388200000001?_skw=iPh...
12099,285595308985,Apple iPhone 13 - 128GB - Pink (AT&T) Excellen...,https://i.ebayimg.com/images/g/7wYAAOSwWfplcOX...,False,Fixed Price,False,https://www.ebay.com/itm/285595308985?_skw=iPh...

In [326]:
#'Country','PostalCode'
Location_Dim=df_updated.loc[:,['Country','PostalCode']]
Location_Dim.to_csv(r'C:\Users\Ahmed\Desktop\DimLocation.csv')
Location_Dim

      Country PostalCode
0          US      757**
1          US      554**
2          US      757**
3          US      917**
4          US      785**
...       ...        ...
12088      US    Unknown
12089      US      334**
12097      US    Unknown
12098      US      770**
12099      US      331**

[10592 rows x 2 columns]

In [327]:
Category_Dim=df_updated.loc[:,['CategoryId','categories']]
Category_Dim.to_csv(r'C:\Users\Ahmed\Desktop\DimCategory.csv')
Category_Dim

       CategoryId                 categories
0             177      PC Laptops & Netbooks
1             177      PC Laptops & Netbooks
2             177      PC Laptops & Netbooks
3             177      PC Laptops & Netbooks
4             177      PC Laptops & Netbooks
...           ...                        ...
12088        9355  Cell Phones & Smartphones
12089        9355  Cell Phones & Smartphones
12097        9355  Cell Phones & Smartphones
12098        9355  Cell Phones & Smartphones
12099        9355  Cell Phones & Smartphones

[10592 rows x 2 columns]

In [328]:
Condition_Dim=df_updated.loc[:,['conditionId','condition','priceDisplayCondition']]
Condition_Dim.to_csv(r'C:\Users\Ahmed\Desktop\DimCondition.csv')
Condition_Dim

      conditionId                condition priceDisplayCondition
0            2030       Good - Refurbished               Unknown
1            3000                     Used               Unknown
2            2030       Good - Refurbished               Unknown
3            3000                     Used               Unknown
4            2000  Certified - Refurbished               Unknown
...           ...                      ...                   ...
12088        3000                     Used               Unknown
12089        3000                     Used               Unknown
12097        1000                      New               Unknown
12098        3000                     Used               Unknown
12099        3000                     Used               Unknown

[10592 rows x 3 columns]

In [329]:
Seller_Dim=df_updated.loc[:,['seller','feedbackPrecentage','feedbackScore']]
Seller_Dim.to_csv(r'C:\Users\Ahmed\Desktop\DimSeller.csv')
Seller_Dim

                      seller  feedbackPrecentage  feedbackScore
0      discountcomputerdepot                99.3         154068
1                 boxdealsco               100.0            603
2      discountcomputerdepot                99.3         154068
3                  yuansheng                97.8           2340
4                       acer                98.9         110846
...                      ...                 ...            ...
12088            yywirelesss                99.5         181920
12089               cruss-42               100.0             20
12097                sdbro-0               100.0              5
12098      houstoncellphones                99.9           1574
12099           fast-connect                98.0           2481

[10592 rows x 3 columns]

In [371]:
Seller_Dim = Seller_Dim.drop_duplicates(subset=['seller'])
Product_Dim = Product_Dim.drop_duplicates(subset=['ProductId'])
Condition_Dim = Condition_Dim.drop_duplicates(subset=['conditionId'])
Category_Dim = Category_Dim.drop_duplicates(subset=['CategoryId'])
Location_Dim=Location_Dim.drop_duplicates(subset=['Country'])

In [395]:
Fact_Table

,ProductId,CategoryId,price,conditionId,originalPrice,discountPercentage,discountAmount,shippingCost,feedbackPrecentage,feedbackScore,currentBidPrice,ProductCreationDateId,ProductOriginDateId,minEstimatedDeliveryDateId,maxEstimatedDeliveryDateId,SellerId,LocationId
0,286393092388,177,303.73,2030,337.48,10,33.75,0.0,99.3,154068,0.0,147812,147812,169471,169467,12370,176
1,177800317663,177,159.99,3000,0.00,0,0.00,0.0,100.0,603,0.0,147145,147145,169468,169469,12371,176
2,256879744174,177,301.2,2030,334.67,10,33.47,0.0,99.3,154068,0.0,147622,147622,169471,169467,12370,176
3,167783058564,177,85.0,3000,0.00,0,0.00,0.0,97.8,2340,0.0,146568,146568,169471,169467,12372,176
4,276709583737,177,371.99,2000,799.99,54,428.00,0.0,98.9,110846,0.0,143810,147571,169471,169467,12373,176
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12088,176485105171,9355,139.99,3000,114.00,-23,-25.99,0.0,99.5,181920,0.0,148284,148284,169471,169468,15920,176
12089,354363592098,9355,299.99,3000,0.00,0,0.00,0.0,100.0,20,0.0,137693,148285,169468,169469,16412,176
12097,137103691849,9355,38.51,1000,0.00,0,0.00,0.0,100.0,5,0.0,148286,148286,169471,169470,16300,176
12098,388200000001,9355,184.0,3000,0.00,0,0.00,0.0,99.9,1574,0.0,148287,148287,168318,169471,15881,176
12099,285595308985,9355,489.0,3000,0.00,0,0.00,0.0,98.0,2481,0.0,148288,148288,169472,169472,16087,176

In [332]:
#Date_Dim=df_updated.loc[:,['productOriginDate','productCreationDate','minEstimatedDeliveryDate','maxEstimatedDeliveryDate']]
#Date_Dim
dates = pd.concat([df_updated['productCreationDate'],df_updated['productOriginDate'],df_updated['minEstimatedDeliveryDate'],df_updated['maxEstimatedDeliveryDate']])
dates = pd.to_datetime(dates, utc=True).dt.tz_localize(None)
DimDate=pd.DataFrame()
DimDate['FullDate']=dates
DimDate['Day']=DimDate['FullDate'].dt.day
DimDate['Month']=DimDate['FullDate'].dt.month
DimDate['Year']=DimDate['FullDate'].dt.year
DimDate['Hour']=DimDate['FullDate'].dt.hour
DimDate['Minute']=DimDate['FullDate'].dt.minute
DimDate['Second']=DimDate['FullDate'].dt.second
DimDate['MonthName']=DimDate['FullDate'].dt.month_name()
DimDate.to_csv(r'C:\Users\Ahmed\Desktop\DimDate2.csv')
DimDate

                 FullDate  Day  Month  Year  Hour  Minute  Second  MonthName
0     2025-03-08 15:50:37    8      3  2025    15      50      37      March
1     2026-01-23 04:59:35   23      1  2026     4      59      35    January
2     2025-04-02 14:32:55    2      4  2025    14      32      55      April
3     2025-09-10 22:56:41   10      9  2025    22      56      41  September
4     2024-10-30 23:21:59   30     10  2024    23      21      59    October
...                   ...  ...    ...   ...   ...     ...     ...        ...
12088 2026-03-12 07:00:00   12      3  2026     7       0       0      March
12089 2026-03-18 07:00:00   18      3  2026     7       0       0      March
12097 2026-03-14 07:00:00   14      3  2026     7       0       0      March
12098 2026-03-11 07:00:00   11      3  2026     7       0       0      March
12099 1970-01-01 00:00:00    1      1  1970     0       0       0    January

[42368 rows x 8 columns]

In [ ]:
if 'currentBidPrice' in df_updated.columns:
    Fact_Table=df_updated.loc[:,['ProductId','CategoryId','price','conditionId','originalPrice','discountPercentage','discountAmount','shippingCost','feedbackPrecentage','feedbackScore','currentBidPrice','productCreationDate','productOriginDate','minEstimatedDeliveryDate','maxEstimatedDeliveryDate','seller','Country']]

else:
    Fact_Table=df_updated.loc[:,['ProductId','CategoryId','price','conditionId','originalPrice','discountPercentage','discountAmount','shippingCost','feedbackPrecentage','feedbackScore','productCreationDate','productOriginDate','minEstimatedDeliveryDate','maxEstimatedDeliveryDate','seller','Country']]

Fact_Table
Fact_Table['productCreationDate'] = Fact_Table['productCreationDate'].dt.date
Fact_Table['productOriginDate'] = Fact_Table['productOriginDate'].dt.date

Fact_Table.to_csv(r'C:\Users\Ahmed\Desktop\FactTable.csv')

In [ ]:
Fact_Table['minEstimatedDeliveryDate'] = pd.to_datetime(
    Fact_Table['minEstimatedDeliveryDate'], errors='coerce', utc=True
)
Fact_Table['maxEstimatedDeliveryDate'] = pd.to_datetime(
    Fact_Table['maxEstimatedDeliveryDate'], errors='coerce', utc=True
)
Fact_Table['minEstimatedDeliveryDate'] = Fact_Table['minEstimatedDeliveryDate'].dt.date
Fact_Table['maxEstimatedDeliveryDate'] = Fact_Table['maxEstimatedDeliveryDate'].dt.date

In [96]:
df_updated.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10592 entries, 0 to 12099
Data columns (total 32 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   ProductId                 10592 non-null  int64
 1   Product                   10592 non-null  object
 2   CategoryId                10592 non-null  int64
 3   categories                10592 non-null  object
 4   image                     10592 non-null  object
 5   price                     10592 non-null  object
 6   seller                    10592 non-null  object
 7   condition                 10592 non-null  object
 8   conditionId               10592 non-null  object
 9   buyingOptions             10592 non-null  object
 10  productWebUrl             10592 non-null  object
 11  adultOnly                 10592 non-null  bool
 12  availableCoupons          10592 non-null  bool
 13  productOriginDate         10592 non-null  datetime64[ns, UTC]
 14  productCreationDate       10592 non-null  datetime64[ns, UTC]
 15  topRatedBuyingExperience  10592 non-null  bool
 16  listingMarketplaceId      10592 non-null  object
 17  priceDisplayCondition     10592 non-null  object
 18  pickupOptions             10592 non-null  object
 19  currentBidPrice           10592 non-null  float64
 20  currency                  10592 non-null  object
 21  shippingCostType          10592 non-null  object
 22  originalPrice             10592 non-null  float64
 23  discountPercentage        10592 non-null  int64
 24  discountAmount            10592 non-null  float64
 25  shippingCost              10592 non-null  object
 26  minEstimatedDeliveryDate  10592 non-null  object
 27  maxEstimatedDeliveryDate  10592 non-null  object
 28  Country                   10592 non-null  object
 29  PostalCode                10592 non-null  object
 30  feedbackPrecentage        10592 non-null  float64
 31  feedbackScore             10592 non-null  int64
dtypes: bool(3), datetime64[ns, UTC](2), float64(4), int64(4), object(19)
memory usage: 2.5+ MB

In [84]:
import pandas as pd
df_updated.to_csv(r'C:\Users\Ahmed\Desktop\eBay_Cleaned.csv')
df_updated

,ProductId,Product,CategoryId,categories,image,price,seller,condition,conditionId,buyingOptions,...,originalPrice,discountPercentage,discountAmount,shippingCost,minEstimatedDeliveryDate,maxEstimatedDeliveryDate,Country,PostalCode,feedbackPrecentage,feedbackScore
0,286393092388,Dell Latitude Laptop Computer PC Intel i5 Up T...,177,PC Laptops & Netbooks,https://i.ebayimg.com/images/g/PcAAAeSwFd1plzs...,303.73,discountcomputerdepot,Good - Refurbished,2030,Fixed Price,...,337.48,10,33.75,0.0,2026-03-11 07:00:00+00:00,2026-03-13 07:00:00+00:00,US,757**,99.3,154068
1,177800317663,"Dell Latitude 5289 2-in-1 12.3"" i5-7600U@2.8GH...",177,PC Laptops & Netbooks,https://i.ebayimg.com/images/g/UmAAAeSwhPZpcvz...,159.99,boxdealsco,Used,3000,Fixed Price and Best Offer,...,0.00,0,0.00,0.0,2026-03-12 07:00:00+00:00,2026-03-18 07:00:00+00:00,US,554**,100.0,603
2,256879744174,Dell Latitude 15.6” FHD Core i5 Laptop PC Up T...,177,PC Laptops & Netbooks,https://i.ebayimg.com/images/g/kSsAAeSw0r5pZ8W...,301.2,discountcomputerdepot,Good - Refurbished,2030,Fixed Price,...,334.67,10,33.47,0.0,2026-03-11 07:00:00+00:00,2026-03-13 07:00:00+00:00,US,757**,99.3,154068
3,167783058564,"HP X360 G2 EE 11"" Laptop Windows 11 Pro Touch ...",177,PC Laptops & Netbooks,https://i.ebayimg.com/images/g/9rwAAeSwuU5owf~...,85.0,yuansheng,Used,3000,Fixed Price and Best Offer,...,0.00,0,0.00,0.0,2026-03-11 07:00:00+00:00,2026-03-13 07:00:00+00:00,US,917**,97.8,2340
4,276709583737,"Acer Swift Go 14"" Laptop Intel Core Ultra 7 15...",177,PC Laptops & Netbooks,https://i.ebayimg.com/images/g/m3YAAeSwJJZpOyM...,371.99,acer,Certified - Refurbished,2000,Fixed Price,...,799.99,54,428.00,0.0,2026-03-11 07:00:00+00:00,2026-03-13 07:00:00+00:00,US,785**,98.9,110846
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12088,176485105171,Apple iPhone 8 A1905 Orange Only 256GB Silver B,9355,Cell Phones & Smartphones,https://i.ebayimg.com/images/g/pNQAAOSwTJhmnw1...,139.99,yywirelesss,Used,3000,Fixed Price,...,114.00,-23,-25.99,0.0,2026-03-11 07:00:00+00:00,2026-03-12 07:00:00+00:00,US,Unknown,99.5,181920
12089,354363592098,Apple iPhone 12 mini - 64GB - White (AT&T),9355,Cell Phones & Smartphones,https://i.ebayimg.com/images/g/3fkAAOSwlWBjVL~...,299.99,cruss-42,Used,3000,Fixed Price and Best Offer,...,0.00,0,0.00,0.0,2026-03-12 07:00:00+00:00,2026-03-18 07:00:00+00:00,US,334**,100.0,20
12097,137103691849,"iPhone 17 Pro Max Case Smooth Crystal Clear, A...",9355,Cell Phones & Smartphones,https://i.ebayimg.com/images/g/YekAAeSwXJ1prA~...,38.51,sdbro-0,New,1000,Fixed Price,...,0.00,0,0.00,0.0,2026-03-11 07:00:00+00:00,2026-03-14 07:00:00+00:00,US,Unknown,100.0,5
12098,388200000001,"Apple iPhone XS 64GB/256GB - Space Gray, Silve...",9355,Cell Phones & Smartphones,https://i.ebayimg.com/images/g/kWMAAOSwieln8Av...,184.0,houstoncellphones,Used,3000,Fixed Price,...,0.00,0,0.00,0.0,2026-03-10 07:00:00+00:00,2026-03-11 07:00:00+00:00,US,770**,99.9,1574
12099,285595308985,Apple iPhone 13 - 128GB - Pink (AT&T) Excellen...,9355,Cell Phones & Smartphones,https://i.ebayimg.com/images/g/7wYAAOSwWfplcOX...,489.0,fast-connect,Used,3000,Fixed Price,...,0.00,0,0.00,0.0,0,0,US,331**,98.0,2481

In [240]:
!pip install pandas sqlalchemy mysql-connector-python
!pip install mysql-connector-python

Requirement already satisfied: pandas in c:\users\ahmed\anaconda3\lib\site-packages (2.2.3)
Requirement already satisfied: sqlalchemy in c:\users\ahmed\anaconda3\lib\site-packages (2.0.39)
Requirement already satisfied: mysql-connector-python in c:\users\ahmed\anaconda3\lib\site-packages (9.6.0)
Requirement already satisfied: numpy>=1.26.0 in c:\users\ahmed\anaconda3\lib\site-packages (from pandas) (2.1.3)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\ahmed\appdata\roaming\python\python313\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\ahmed\anaconda3\lib\site-packages (from pandas) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\ahmed\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: greenlet!=0.4.17 in c:\users\ahmed\anaconda3\lib\site-packages (from sqlalchemy) (3.1.1)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\ahmed\anaconda3\lib\site-packages (from sqlalchemy) (4.12.2)
Requirement already satisfied: six>=1.5 in c:\users\ahmed\appdata\roaming\python\python313\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: mysql-connector-python in c:\users\ahmed\anaconda3\lib\site-packages (9.6.0)

In [353]:
import mysql.connector
from sqlalchemy import create_engine

conn = mysql.connector.connect(
  host="localhost",
  user="root",
  password="Medoahmed1992"
)
cursor = conn.cursor()
cursor.execute("USE depi")
cursor.execute('''
CREATE TABLE IF NOT EXISTS DimDate (
    DateId INT AUTO_INCREMENT PRIMARY KEY,
    FullDate Date,
    Day int,
  Month INT,
               Year INT,
               Hour INT,
               Minute INT,
               Second INT,
               MonthName VARCHAR(100)
)
''')
user = "root"
password = "Medoahmed1992"
host = "localhost"
database = "depi"
engine = create_engine(f"mysql+mysqlconnector://{user}:{password}@{host}/{database}")
DimDate.to_sql(
    name='DimDate',   # Table name in MySQL
    con=engine,        # Connection engine
    if_exists='append',  # 'replace' = overwrite table, 'append' = add rows
    index=False        # Do not write DataFrame index as a column
)



conn.commit()

C:\Users\Ahmed\AppData\Local\Temp\ipykernel_32672\3254358430.py:29: UserWarning: The provided table name 'DimDate' is not found exactly as such in the database after writing the table, possibly due to case sensitivity issues. Consider using lower case table names.
  DimDate.to_sql(

In [354]:
cursor.execute("USE depi")
cursor.execute('''
CREATE TABLE IF NOT EXISTS DimLocation (
    LocationId INT AUTO_INCREMENT PRIMARY KEY,
    Country TEXT,
    PostalCode TEXT
)
''')

Location_Dim.to_sql(
    name='DimLocation',   # Table name in MySQL
    con=engine,        # Connection engine
    if_exists='append',  # 'replace' = overwrite table, 'append' = add rows
    index=False        # Do not write DataFrame index as a column
)

C:\Users\Ahmed\AppData\Local\Temp\ipykernel_32672\3652211004.py:10: UserWarning: The provided table name 'DimLocation' is not found exactly as such in the database after writing the table, possibly due to case sensitivity issues. Consider using lower case table names.
  Location_Dim.to_sql(

35

In [391]:
Location_Dim.to_sql(
    name='DimLocation',   # Table name in MySQL
    con=engine,        # Connection engine
    if_exists='append',  # 'replace' = overwrite table, 'append' = add rows
    index=False        # Do not write DataFrame index as a column
)
Location_Dim_mysql = pd.read_sql("SELECT * FROM DimLocation", con=engine)

location_map = dict(zip(Location_Dim_mysql['Country'], Location_Dim_mysql['LocationId']))

Fact_Table['LocationId'] = Fact_Table['Country'].map(location_map)

C:\Users\Ahmed\AppData\Local\Temp\ipykernel_32672\1171842953.py:1: UserWarning: The provided table name 'DimLocation' is not found exactly as such in the database after writing the table, possibly due to case sensitivity issues. Consider using lower case table names.
  Location_Dim.to_sql(

In [389]:
# Insert the DimDate DataFrame into MySQL
DimDate.to_sql(
    name='DimDate',
    con=engine,
    if_exists='append',
    index=False
)

# Fetch the table back with DateId
DimDate_mysql = pd.read_sql("SELECT * FROM DimDate", con=engine)

# Now you have DateId for mapping
date_id_map = dict(zip(DimDate_mysql['FullDate'], DimDate_mysql['DateId']))

# Map to fact table
Fact_Table['ProductCreationDateId'] = Fact_Table['productCreationDate'].map(date_id_map)
Fact_Table['ProductOriginDateId'] = Fact_Table['productOriginDate'].map(date_id_map)
Fact_Table['minEstimatedDeliveryDateId'] = Fact_Table['minEstimatedDeliveryDate'].map(date_id_map)
Fact_Table['maxEstimatedDeliveryDateId'] = Fact_Table['maxEstimatedDeliveryDate'].map(date_id_map)

C:\Users\Ahmed\AppData\Local\Temp\ipykernel_32672\3983157772.py:2: UserWarning: The provided table name 'DimDate' is not found exactly as such in the database after writing the table, possibly due to case sensitivity issues. Consider using lower case table names.
  DimDate.to_sql(

In [359]:
cursor.execute("USE depi")
cursor.execute('''
CREATE TABLE IF NOT EXISTS DimSeller (
    SellerId INT AUTO_INCREMENT PRIMARY KEY,
    Seller VARCHAR(200),
    Country VARCHAR(200),
  PostalCode VARCHAR(100),
               FeedbackPrecentage FLOAT,
               FeedbackScore INT
)
''')
Seller_Dim.to_sql(
    name='DimSeller',   # Table name in MySQL
    con=engine,        # Connection engine
    if_exists='append',  # 'replace' = overwrite table, 'append' = add rows
    index=False        # Do not write DataFrame index as a column
)

C:\Users\Ahmed\AppData\Local\Temp\ipykernel_32672\935089593.py:12: UserWarning: The provided table name 'DimSeller' is not found exactly as such in the database after writing the table, possibly due to case sensitivity issues. Consider using lower case table names.
  Seller_Dim.to_sql(

4123

In [390]:
Seller_Dim.to_sql(
    name='DimSeller',
    con=engine,
    if_exists='append',
    index=False
)

Seller_Dim_mysql = pd.read_sql("SELECT * FROM DimSeller", con=engine)

seller_map = dict(zip(Seller_Dim_mysql['Seller'], Seller_Dim_mysql['SellerId']))

Fact_Table['SellerId'] = Fact_Table['seller'].map(seller_map)

C:\Users\Ahmed\AppData\Local\Temp\ipykernel_32672\1220439700.py:1: UserWarning: The provided table name 'DimSeller' is not found exactly as such in the database after writing the table, possibly due to case sensitivity issues. Consider using lower case table names.
  Seller_Dim.to_sql(

In [392]:
Fact_Table
Fact_Table=Fact_Table.drop('productCreationDate',axis=1)
Fact_Table=Fact_Table.drop('productOriginDate',axis=1)
Fact_Table=Fact_Table.drop('maxEstimatedDeliveryDate',axis=1)
Fact_Table=Fact_Table.drop('minEstimatedDeliveryDate',axis=1)
Fact_Table=Fact_Table.drop('seller',axis=1)
Fact_Table=Fact_Table.drop('Country',axis=1)

In [276]:
Seller_Dim

,seller,Country,PostalCode,feedbackPrecentage,feedbackScore
0,discountcomputerdepot,US,757**,99.3,154068
1,boxdealsco,US,554**,100.0,603
3,yuansheng,US,917**,97.8,2340
4,acer,US,785**,98.9,110846
5,toyarcade,US,631**,99.3,76313
...,...,...,...,...,...
12063,jaridel0,US,181**,0.0,5
12064,jayce_morris,US,190**,0.0,0
12065,mobilemarvel,US,900**,98.8,3047
12066,jemjem_certified,US,Unknown,97.7,11537
12079,martin21_4,US,752**,0.0,0

In [277]:

Condition_Dim

     conditionId                 condition priceDisplayCondition
0           2030        Good - Refurbished               Unknown
1           3000                      Used               Unknown
4           2000   Certified - Refurbished               Unknown
16          1000                       New               Unknown
18          2010   Excellent - Refurbished               Unknown
23          1500                  Open box               Unknown
37          2020   Very Good - Refurbished               Unknown
210         7000  For parts or not working               Unknown
5926        4000                 Very Good               Unknown

In [24]:
DimDate.to_csv(r'C:\Users\Ahmed\Desktop\DimDate2.csv')

In [30]:
!pip install mysql-connector-python

Requirement already satisfied: mysql-connector-python in c:\users\ahmed\anaconda3\lib\site-packages (9.6.0)

In [278]:
DimDate

                 FullDate  Day  Month  Year  Hour  Minute  Second  MonthName
0     2025-03-08 15:50:37    8      3  2025    15      50      37      March
1     2026-01-23 04:59:35   23      1  2026     4      59      35    January
2     2025-04-02 14:32:55    2      4  2025    14      32      55      April
3     2025-09-10 22:56:41   10      9  2025    22      56      41  September
4     2024-10-30 23:21:59   30     10  2024    23      21      59    October
...                   ...  ...    ...   ...   ...     ...     ...        ...
12088 2026-03-12 07:00:00   12      3  2026     7       0       0      March
12089 2026-03-18 07:00:00   18      3  2026     7       0       0      March
12097 2026-03-14 07:00:00   14      3  2026     7       0       0      March
12098 2026-03-11 07:00:00   11      3  2026     7       0       0      March
12099 1970-01-01 00:00:00    1      1  1970     0       0       0    January

[42368 rows x 8 columns]

In [69]:
!pip install pandas sqlalchemy mysql-connector-python

Requirement already satisfied: pandas in c:\users\ahmed\anaconda3\lib\site-packages (2.2.3)
Requirement already satisfied: sqlalchemy in c:\users\ahmed\anaconda3\lib\site-packages (2.0.39)
Requirement already satisfied: mysql-connector-python in c:\users\ahmed\anaconda3\lib\site-packages (9.6.0)
Requirement already satisfied: numpy>=1.26.0 in c:\users\ahmed\anaconda3\lib\site-packages (from pandas) (2.1.3)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\ahmed\appdata\roaming\python\python313\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\ahmed\anaconda3\lib\site-packages (from pandas) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\ahmed\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: greenlet!=0.4.17 in c:\users\ahmed\anaconda3\lib\site-packages (from sqlalchemy) (3.1.1)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\ahmed\anaconda3\lib\site-packages (from sqlalchemy) (4.12.2)
Requirement already satisfied: six>=1.5 in c:\users\ahmed\appdata\roaming\python\python313\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [100]:
conn.commit()

In [363]:
cursor.execute("USE depi")
cursor.execute('''
CREATE TABLE IF NOT EXISTS DimProduct (
    ProductId BIGINT PRIMARY KEY,
    Product TEXT,
    Image TEXT,
  AdultOnly BOOLEAN,
               BuyingOptions varchar(500),
               AvailableCoupons BOOLEAN,
               ProductWebURL TEXT
)
''')

In [364]:
Product_Dim.to_sql(
    name='DimProduct',   # Table name in MySQL
    con=engine,        # Connection engine
    if_exists='append',  # 'replace' = overwrite table, 'append' = add rows
    index=False        # Do not write DataFrame index as a column
)

C:\Users\Ahmed\AppData\Local\Temp\ipykernel_32672\1910535861.py:1: UserWarning: The provided table name 'DimProduct' is not found exactly as such in the database after writing the table, possibly due to case sensitivity issues. Consider using lower case table names.
  Product_Dim.to_sql(

9706

In [365]:

cursor.execute("USE depi")
cursor.execute('''
CREATE TABLE IF NOT EXISTS DimCondition (
     ConditionId BIGINT PRIMARY KEY,
    ConditionType TEXT,
    priceDisplayCondition TEXT
)
''')

In [366]:
Condition_Dim.rename(columns={'condition': 'conditionType'}, inplace=True)
Condition_Dim.to_sql(
    name='DimCondition',   # Table name in MySQL
    con=engine,        # Connection engine
    if_exists='append',  # 'replace' = overwrite table, 'append' = add rows
    index=False        # Do not write DataFrame index as a column
)

C:\Users\Ahmed\AppData\Local\Temp\ipykernel_32672\4260801231.py:2: UserWarning: The provided table name 'DimCondition' is not found exactly as such in the database after writing the table, possibly due to case sensitivity issues. Consider using lower case table names.
  Condition_Dim.to_sql(

9

In [367]:

cursor.execute("USE depi")
cursor.execute('''
CREATE TABLE IF NOT EXISTS DimCategory (
     CategoryId BIGINT PRIMARY KEY,
    Categories TEXT
    
)
''')

In [368]:
Category_Dim.to_sql(
    name='DimCategory',   # Table name in MySQL
    con=engine,        # Connection engine
    if_exists='append',  # 'replace' = overwrite table, 'append' = add rows
    index=False        # Do not write DataFrame index as a column
)

C:\Users\Ahmed\AppData\Local\Temp\ipykernel_32672\1743254496.py:1: UserWarning: The provided table name 'DimCategory' is not found exactly as such in the database after writing the table, possibly due to case sensitivity issues. Consider using lower case table names.
  Category_Dim.to_sql(

22

In [348]:
Fact_Table

,ProductId,CategoryId,price,conditionId,originalPrice,discountPercentage,discountAmount,shippingCost,feedbackPrecentage,feedbackScore,currentBidPrice,ProductCreationDateId,ProductOriginDateId,minEstimatedDeliveryDateId,maxEstimatedDeliveryDateId,SellerId,LocationId
0,286393092388,177,303.73,2030,337.48,10,33.75,0.0,99.3,154068,0.0,63076,63076,84735,84731,4124,36
1,177800317663,177,159.99,3000,0.00,0,0.00,0.0,100.0,603,0.0,62409,62409,84732,84733,4125,36
2,256879744174,177,301.2,2030,334.67,10,33.47,0.0,99.3,154068,0.0,62886,62886,84735,84731,4124,36
3,167783058564,177,85.0,3000,0.00,0,0.00,0.0,97.8,2340,0.0,61832,61832,84735,84731,4126,36
4,276709583737,177,371.99,2000,799.99,54,428.00,0.0,98.9,110846,0.0,59074,62835,84735,84731,4127,36
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12088,176485105171,9355,139.99,3000,114.00,-23,-25.99,0.0,99.5,181920,0.0,63548,63548,84735,84732,7674,36
12089,354363592098,9355,299.99,3000,0.00,0,0.00,0.0,100.0,20,0.0,52957,63549,84732,84733,8166,36
12097,137103691849,9355,38.51,1000,0.00,0,0.00,0.0,100.0,5,0.0,63550,63550,84735,84734,8054,36
12098,388200000001,9355,184.0,3000,0.00,0,0.00,0.0,99.9,1574,0.0,63551,63551,83582,84735,7635,36
12099,285595308985,9355,489.0,3000,0.00,0,0.00,0.0,98.0,2481,0.0,63552,63552,84736,84736,7841,36

In [393]:
cursor.execute("USE depi") #minEstimatedDeliveryDateId
cursor.execute('''
CREATE TABLE IF NOT EXISTS FactTable (
               ProductCreationDateId INT,
    ProductOriginDateId INT,
    minEstimatedDeliveryDateId INT,
    maxEstimatedDeliveryDateId INT,
              
               ProductId BIGINT,
    CategoryId BIGINT,
    ConditionId BIGINT,
               SellerId INT,
               LocationId INT,
               FOREIGN KEY (LocationId) REFERENCES DimLocation(LocationId),
               FOREIGN KEY (SellerId) REFERENCES DimSeller(SellerId),
     FOREIGN KEY (ProductCreationDateId) REFERENCES DimDate(DateId),
               FOREIGN KEY (ProductOriginDateId) REFERENCES DimDate(DateId),
               FOREIGN KEY (ProductOriginDateId) REFERENCES DimDate(DateId),
               FOREIGN KEY (minEstimatedDeliveryDateId) REFERENCES DimDate(DateId),
               FOREIGN KEY (maxEstimatedDeliveryDateId) REFERENCES DimDate(DateId),
               FOREIGN KEY (ProductId) REFERENCES DimProduct(ProductId),
               FOREIGN KEY (CategoryId) REFERENCES DimCategory(CategoryId),
               Price FLOAT,
               FOREIGN KEY (ConditionId) REFERENCES DimCondition(ConditionId),
               OriginalPrice FLOAT,
               DiscountPercentage INT,
               DiscountAmount FLOAT,
               ShippingCost FLOAT,
               FeedbackPrecentage FLOAT,
               FeedbackScore INT,
               CurrentBidPrice FLOAT
               
)
''')

In [394]:
Fact_Table.to_sql(
    name='FactTable',   # Table name in MySQL
    con=engine,        # Connection engine
    if_exists='append',  # 'replace' = overwrite table, 'append' = add rows
    index=False        # Do not write DataFrame index as a column
)

C:\Users\Ahmed\AppData\Local\Temp\ipykernel_32672\3138578515.py:1: UserWarning: The provided table name 'FactTable' is not found exactly as such in the database after writing the table, possibly due to case sensitivity issues. Consider using lower case table names.
  Fact_Table.to_sql(

10592

In [398]:
Seller_Dim.to_csv(r'C:\Users\Ahmed\Desktop\DimSeller2.csv')
Seller_Dim

                      seller  feedbackPrecentage  feedbackScore
0      discountcomputerdepot                99.3         154068
1                 boxdealsco               100.0            603
3                  yuansheng                97.8           2340
4                       acer                98.9         110846
5                  toyarcade                99.3          76313
...                      ...                 ...            ...
12054             sparks_224               100.0              7
12063               jaridel0                 0.0              5
12064           jayce_morris                 0.0              0
12066       jemjem_certified                97.7          11537
12079             martin21_4                 0.0              0

[4123 rows x 3 columns]

In [399]:
Fact_Table.to_csv(r'C:\Users\Ahmed\Desktop\FactTable2.csv')
Fact_Table

,ProductId,CategoryId,price,conditionId,originalPrice,discountPercentage,discountAmount,shippingCost,feedbackPrecentage,feedbackScore,currentBidPrice,ProductCreationDateId,ProductOriginDateId,minEstimatedDeliveryDateId,maxEstimatedDeliveryDateId,SellerId,LocationId
0,286393092388,177,303.73,2030,337.48,10,33.75,0.0,99.3,154068,0.0,147812,147812,169471,169467,12370,176
1,177800317663,177,159.99,3000,0.00,0,0.00,0.0,100.0,603,0.0,147145,147145,169468,169469,12371,176
2,256879744174,177,301.2,2030,334.67,10,33.47,0.0,99.3,154068,0.0,147622,147622,169471,169467,12370,176
3,167783058564,177,85.0,3000,0.00,0,0.00,0.0,97.8,2340,0.0,146568,146568,169471,169467,12372,176
4,276709583737,177,371.99,2000,799.99,54,428.00,0.0,98.9,110846,0.0,143810,147571,169471,169467,12373,176
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12088,176485105171,9355,139.99,3000,114.00,-23,-25.99,0.0,99.5,181920,0.0,148284,148284,169471,169468,15920,176
12089,354363592098,9355,299.99,3000,0.00,0,0.00,0.0,100.0,20,0.0,137693,148285,169468,169469,16412,176
12097,137103691849,9355,38.51,1000,0.00,0,0.00,0.0,100.0,5,0.0,148286,148286,169471,169470,16300,176
12098,388200000001,9355,184.0,3000,0.00,0,0.00,0.0,99.9,1574,0.0,148287,148287,168318,169471,15881,176
12099,285595308985,9355,489.0,3000,0.00,0,0.00,0.0,98.0,2481,0.0,148288,148288,169472,169472,16087,176

In [400]:
Condition_Dim.to_csv(r'C:\Users\Ahmed\Desktop\DimCondition2.csv')
Condition_Dim

     conditionId             conditionType priceDisplayCondition
0           2030        Good - Refurbished               Unknown
1           3000                      Used               Unknown
4           2000   Certified - Refurbished               Unknown
16          1000                       New               Unknown
18          2010   Excellent - Refurbished               Unknown
23          1500                  Open box               Unknown
37          2020   Very Good - Refurbished               Unknown
210         7000  For parts or not working               Unknown
5926        4000                 Very Good               Unknown

In [401]:
Category_Dim.to_csv(r'C:\Users\Ahmed\Desktop\DimCategory2.csv')
Category_Dim

       CategoryId                     categories
0             177          PC Laptops & Netbooks
580        111422                  Apple Laptops
733        171485        Tablets & eBook Readers
2775       131542       CD, DVD & Blu-ray Drives
3157        56083      Internal Hard Disk Drives
4001        51071               USB Flash Drives
4367        16145       Other Components & Parts
5000       139971            Video Game Consoles
5134        31388                Digital Cameras
5926       139973                    Video Games
6440       171833      Replacement Parts & Tools
6980        13716          Video Arcade Machines
7489        11071                            TVs
7825       111694    Audio Docks & Mini Speakers
8748        11724                     Camcorders
9000         9355      Cell Phones & Smartphones
9036        43304  Cell Phone & Smartphone Parts
9153       123422              Cables & Adapters
9224        20349          Cases, Covers & Skins
10280      123417             Chargers & Cradles
10589       58540              Screen Protectors
10798       80077                       Headsets

In [402]:
Location_Dim.to_csv(r'C:\Users\Ahmed\Desktop\DimLocation2.csv')
Location_Dim

      Country PostalCode
0          US      757**
25         ES      28***
648        GB     CR0***
858        JP    Unknown
1099       AU       2***
1165       AZ    Unknown
1384       CA     L3R***
1838       IT      90***
2474       CN    Unknown
2545       KR    Unknown
2922       HR    Unknown
3175       DK    Unknown
3519       PR    Unknown
3877       LT    Unknown
4310       VI    Unknown
4628       AE    Unknown
4657       FR      94***
4891       NL     25****
4905       EE    Unknown
5565       VN    Unknown
5885       OM      *****
5911       TH    Unknown
6531       HK    Unknown
6586       DE      74***
6752       JO    Unknown
7928       IN     ******
7990       AL    Unknown
8544       GR    Unknown
8834       UA    Unknown
8990       ID    Unknown
10356      PL      01***
10855      SI       ****
11168      BG    Unknown
11344      TW    Unknown
12049      JM    Unknown

In [403]:
DimDate.to_csv(r'C:\Users\Ahmed\Desktop\DimDate2.csv')
DimDate

                 FullDate  Day  Month  Year  Hour  Minute  Second  MonthName
0     2025-03-08 15:50:37    8      3  2025    15      50      37      March
1     2026-01-23 04:59:35   23      1  2026     4      59      35    January
2     2025-04-02 14:32:55    2      4  2025    14      32      55      April
3     2025-09-10 22:56:41   10      9  2025    22      56      41  September
4     2024-10-30 23:21:59   30     10  2024    23      21      59    October
...                   ...  ...    ...   ...   ...     ...     ...        ...
12088 2026-03-12 07:00:00   12      3  2026     7       0       0      March
12089 2026-03-18 07:00:00   18      3  2026     7       0       0      March
12097 2026-03-14 07:00:00   14      3  2026     7       0       0      March
12098 2026-03-11 07:00:00   11      3  2026     7       0       0      March
12099 1970-01-01 00:00:00    1      1  1970     0       0       0    January

[42368 rows x 8 columns]