In [ ]:
import requests # get post put patch APIS
client_id = ""
client_secret = ""

url = "https://api.ebay.com/identity/v1/oauth2/token"
data = {
    "grant_type": "client_credentials",
    "scope": "https://api.ebay.com/oauth/api_scope"
}

response= requests.post(url,
                       auth=(client_id,client_secret),
                       data=data)


token = response.json()["access_token"]
print(token)

v^1.1#i^1#p^1#I^3#f^0#r^0#t^H4sIAAAAAAAA/+VYfWwURRS/a68VBISoEYJIjwWUoLu3u7f3sQt34WiptNAPuKNgjZK53dl2ub3d7c4evUYCpUDBRP4BG0MwATEmhFQSE4ypBPADJIKiEgkRNCBRQ2JM/CA0gEZn745yrYQiPeMlXja57Js3b97v996beTt0Z/no2d0Lu/vHOe8r2d1Jd5Y4ncwYenR52ZMPlJZMLnPQeQrO3Z0zOl1dpZfnIpBUDWEpRIauIehOJ1UNCRlhiEiZmqADpCBBA0mIBEsUopG6xQJL0YJh6pYu6irhrqkKEVLAH5Tjoj/uE0WZ44JYqt20GdNDhE/mvF6vDCAvB+R4gMHjCKVgjYYsoFkhgqVZP0njh48xnMAEBC9LsUG+mXA3QRMpuoZVKJoIZ9wVMnPNPF/v7CpACJoWNkKEayLV0YZITdWC+thcT56tcI6HqAWsFBr8VqlL0N0E1BS88zIooy1EU6IIESI84ewKg40KkZvO3IP7GapBMA7igOEgHwc+SeILQmW1biaBdWc/bIkikXJGVYCapVgdwzGK2YivgqKVe6vHJmqq3PbfkhRQFVmBZohYMD/yTKSxkQjXAg0sagUquUDUk0loimTj0ioSclDiaBiQSJb3Bzm/T8otlLWWo3nISpW6Jik2achdr1vzIfYaDuWGzuMGKzVoDWZEtmyP8vX8AxxyzXZQs1FMWa2aHVeYxES4M6/DR2BgtmWZSjxlwQELQwcyFOFYG4YiEUMHM7mYS580ChGtlmUIHk97ezvV7qV0s8XD0jTjWVG3OCq2wiQgsK5d61l9ZfgJpJKBIkI8EymC1WFgX9I4V7EDWgsR9vl4Hx3M8T7YrfBQ6d8EeZg9gyuiUBXCSCLr8zKs5Idenmd8haiQcC5JPbYfMA46yCQwE9AyVCBCUsR5lsIJq0iC1yez3qAMScnPyyTHyzIZ90l+kpEhpCGMx0U++H8qlLtN9SgUTWgVJNcLluctYosR1aAHrQIa8kpcOqDxXrWtztcUaWMBw+vLAkb9QqlJZcXQ3VbDbcFXqgpmJobXLwQBdq0XjoSFOrKgNCJ4UVE3YKOuKmJHcQXYa0qNwLQ6olBVsWBEICOGUVOYvbpg8P7hNnFvuAt3Rv1H59NtUSE7ZYsLlT0fYQPAUCj7BKJwUD12resAtx+2eGXG6xHhVnDnWlSoMcgsWkXKtpxUBi6FVouUCZGeMnG3TTXYHVhMT0ANn2eWqasqNJuYEddzMpmyQFyFxVbYBUhwBRTZYcsEggzN4O2IHREuMXOUriy2LakQW7GryzltWPxLIVCTxYXdMHUpJdo95r/wyeAZfIERdmR+TJfzA7rLebjE6aTn0jOZ6fS08tJlrtKxk5FiQUoBMoWUFg1/l5uQSsAOAyhmyUOOE2e+qp96sHbvi99N7Nw0w7PN8UDe/cnu5+hJAzcoo0uZMXnXKfSUWyNlzPiJ41g/7ad5hmMCXraZnn5r1MU84nqYJRPCzr1oY+Wpj7Ze/WTdhEW/9F+kxw0oOZ1lDhxsx6z71257go45frpwvNf5+Y5A/PvkO31/CBPeOPvDoT9rXX3s79SuedHfKp4OXT8nbq6s2FE668qjPx9IHG+LHNyP0u7Tta6xBx47Npubc3ZL24qN+lOjdnWfDn4zaatx3a141/ZM2bMzXXH55V7n9LfPfPjstPXfHri4rnx5tTI+ejSx79er7zE33r80p+fk16nuhlPHtu1bM2rxF81HVvfceH39hbLeE4dPvvL4UXnVlQkbXv20KX3tY2ZF9ZbPDlW/dG7s1fC7/XXb+4L1OwOp5subjQevvVW+Z/Jrkd6288FE2bkN63ac56Y+v/zSpjXrZ6yVTp/8sadv5ptL5jWHvjy0fc4RR0WsX+3r33/lhWws/wJD5Hna2RIAAA==

In [2]:
import pandas as pd
search_url = "https://api.ebay.com/buy/browse/v1/item_summary/search" #API browse
y =input("Enter the theme for your product:")
x=int(input("How many items do you want to fetch?"))

all_items=[]
limit=50
total_needed=x

for offset in range(0, total_needed, 50):
    response = requests.get(
        "https://api.ebay.com/buy/browse/v1/item_summary/search",
        params={
            "q": y,
            "limit": 50,
            "offset": offset
        },
        headers={
            "Authorization": f"Bearer {token}"
        }
    )
    data = response.json()
    all_items.extend(data.get('itemSummaries', []))


df=pd.DataFrame(all_items)
df

,itemId,title,leafCategoryIds,categories,image,price,itemHref,seller,condition,conditionId,...,listingMarketplaceId,marketingPrice,itemGroupHref,itemGroupType,epid,pickupOptions,priceDisplayCondition,bidCount,currentBidPrice,itemEndDate
0,v1|256245941032|0,"Dell Latitude 3190 Laptop 11.6"" Intel Celeron ...",[177],"[{'categoryId': '177', 'categoryName': 'PC Lap...",{'imageUrl': 'https://i.ebayimg.com/images/g/U...,"{'value': '119.25', 'currency': 'USD'}",https://api.ebay.com/buy/browse/v1/item/v1%7C2...,"{'username': 'discountcomputerdepot', 'feedbac...",Good - Refurbished,2030,...,EBAY_US,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,v1|254078693996|0,"HP ProBook Touchscreen Laptop 11.6"" Core i3 8G...",[177],"[{'categoryId': '177', 'categoryName': 'PC Lap...",{'imageUrl': 'https://i.ebayimg.com/images/g/e...,"{'value': '149.07', 'currency': 'USD'}",https://api.ebay.com/buy/browse/v1/item/v1%7C2...,"{'username': 'discountcomputerdepot', 'feedbac...",Good - Refurbished,2030,...,EBAY_US,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,v1|116841881853|0,EXECUTIVE SPECIAL~ 15.6 DELL Latitude Laptop: ...,[177],"[{'categoryId': '177', 'categoryName': 'PC Lap...",{'imageUrl': 'https://i.ebayimg.com/images/g/3...,"{'value': '409.95', 'currency': 'USD'}",https://api.ebay.com/buy/browse/v1/item/v1%7C1...,"{'username': 'regadget', 'feedbackPercentage':...",Excellent - Refurbished,2010,...,EBAY_US,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,v1|254654754368|0,"Dell Latitude Touchscreen Laptop 11.6"" Pentium...",[177],"[{'categoryId': '177', 'categoryName': 'PC Lap...",{'imageUrl': 'https://i.ebayimg.com/images/g/g...,"{'value': '150.91', 'currency': 'USD'}",https://api.ebay.com/buy/browse/v1/item/v1%7C2...,"{'username': 'discountcomputerdepot', 'feedbac...",Good - Refurbished,2030,...,EBAY_US,"{'originalPrice': {'value': '795.00', 'currenc...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,v1|235711075450|0,"Windows 11 PRO Laptop Notebook PC Computer, 8G...",[177],"[{'categoryId': '177', 'categoryName': 'PC Lap...",{'imageUrl': 'https://i.ebayimg.com/images/g/K...,"{'value': '122.00', 'currency': 'USD'}",https://api.ebay.com/buy/browse/v1/item/v1%7C2...,"{'username': 'ticktock1-2-3', 'feedbackPercent...",Used,3000,...,EBAY_US,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,v1|287384161048|0,"Dell Latitude 5430 14"" FHD i7-1265U 1.8GHz 512...",[177],"[{'categoryId': '177', 'categoryName': 'PC Lap...",{'imageUrl': 'https://i.ebayimg.com/images/g/-...,"{'value': '369.97', 'currency': 'USD'}",https://api.ebay.com/buy/browse/v1/item/v1%7C2...,"{'username': 'epc-pa', 'feedbackPercentage': '...",Used,3000,...,EBAY_US,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
496,v1|366467034144|0,Microsoft Surface Laptop 4 i7-1185G7 512GB SSD...,[177],"[{'categoryId': '177', 'categoryName': 'PC Lap...",{'imageUrl': 'https://i.ebayimg.com/images/g/2...,"{'value': '299.00', 'currency': 'USD'}",https://api.ebay.com/buy/browse/v1/item/v1%7C3...,"{'username': 'resellelectronics', 'feedbackPer...",Used,3000,...,EBAY_US,NaN,NaN,NaN,17054068852,NaN,NaN,NaN,NaN,NaN
497,v1|226052371811|0,"Lenovo ThinkPad T480 14"" HD i5 8250u 16GB 256g...",[177],"[{'categoryId': '177', 'categoryName': 'PC Lap...",{'imageUrl': 'https://i.ebayimg.com/images/g/r...,"{'value': '299.99', 'currency': 'USD'}",https://api.ebay.com/buy/browse/v1/item/v1%7C2...,"{'username': 'kl0', 'feedbackPercentage': '99....",Excellent - Refurbished,2010,...,EBAY_US,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
498,v1|157981942769|0,"Lenovo IdeaPad 5i 16"" Touch Intel Core Ultra 5...",[177],"[{'categoryId': '177', 'categoryName': 'PC Lap...",{'imageUrl': 'https://i.ebayimg.com/images/g/E...,"{'value': '427.50', 'currency': 'USD'}",https://api.ebay.com/buy/browse/v1/item/v1%7C1...,"{'username': 'jkcomputerparts', 'feedbackPerce...",Used,3000,...,EBAY_US,"{'originalPrice': {'value': '450.00', 'currenc...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
499,v1|137393305219|0,"IdeaPad 5i 2-in-1 14"" Touch Intel Core i5 120U...",[177],"[{'categoryId': '177', 'categoryName': 'PC Lap...",{'imageUrl': 'https://i.ebayimg.com/images/g/j...,"{'value': '370.49', 'currency': 'USD'}",https://api.ebay.com/buy/browse/v1/item/v1%7C1...,"{'username': 'jkcomputerparts', 'feedbackPerce...",Used,3000,...,EBAY_US,"{'originalPrice': {'value': '389.99', 'currenc...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
import requests
import pandas as pd
itms = []

while True:
    z = input("Do you want to add a theme? (Y/N):").upper()
    if z != "Y":
        break
    
    p = input("Enter the theme for your product:")
    q = int(input("How many items do you want to fetch?"))
    
    
    limit = 50
    for offset in range(0, q, limit):
        response = requests.get(
            "https://api.ebay.com/buy/browse/v1/item_summary/search",
            params={
                "q": p,
                "limit": limit,
                "offset": offset
            },
            headers={
                "Authorization": f"Bearer {token}"
            }
        )
        data = response.json()
        itms.extend(data.get('itemSummaries', []))

print(f"Total items fetched: {len(itms)}")
df1=pd.DataFrame(itms)
df_all=pd.concat([df,df1],ignore_index=True)
if len(itms)==0:
    df_all=df

Total items fetched: 500

In [4]:
df_all

,itemId,title,leafCategoryIds,categories,image,price,itemHref,seller,condition,conditionId,...,listingMarketplaceId,marketingPrice,itemGroupHref,itemGroupType,epid,pickupOptions,priceDisplayCondition,bidCount,currentBidPrice,itemEndDate
0,v1|256245941032|0,"Dell Latitude 3190 Laptop 11.6"" Intel Celeron ...",[177],"[{'categoryId': '177', 'categoryName': 'PC Lap...",{'imageUrl': 'https://i.ebayimg.com/images/g/U...,"{'value': '119.25', 'currency': 'USD'}",https://api.ebay.com/buy/browse/v1/item/v1%7C2...,"{'username': 'discountcomputerdepot', 'feedbac...",Good - Refurbished,2030,...,EBAY_US,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,v1|254078693996|0,"HP ProBook Touchscreen Laptop 11.6"" Core i3 8G...",[177],"[{'categoryId': '177', 'categoryName': 'PC Lap...",{'imageUrl': 'https://i.ebayimg.com/images/g/e...,"{'value': '149.07', 'currency': 'USD'}",https://api.ebay.com/buy/browse/v1/item/v1%7C2...,"{'username': 'discountcomputerdepot', 'feedbac...",Good - Refurbished,2030,...,EBAY_US,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,v1|116841881853|0,EXECUTIVE SPECIAL~ 15.6 DELL Latitude Laptop: ...,[177],"[{'categoryId': '177', 'categoryName': 'PC Lap...",{'imageUrl': 'https://i.ebayimg.com/images/g/3...,"{'value': '409.95', 'currency': 'USD'}",https://api.ebay.com/buy/browse/v1/item/v1%7C1...,"{'username': 'regadget', 'feedbackPercentage':...",Excellent - Refurbished,2010,...,EBAY_US,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,v1|254654754368|0,"Dell Latitude Touchscreen Laptop 11.6"" Pentium...",[177],"[{'categoryId': '177', 'categoryName': 'PC Lap...",{'imageUrl': 'https://i.ebayimg.com/images/g/g...,"{'value': '150.91', 'currency': 'USD'}",https://api.ebay.com/buy/browse/v1/item/v1%7C2...,"{'username': 'discountcomputerdepot', 'feedbac...",Good - Refurbished,2030,...,EBAY_US,"{'originalPrice': {'value': '795.00', 'currenc...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,v1|235711075450|0,"Windows 11 PRO Laptop Notebook PC Computer, 8G...",[177],"[{'categoryId': '177', 'categoryName': 'PC Lap...",{'imageUrl': 'https://i.ebayimg.com/images/g/K...,"{'value': '122.00', 'currency': 'USD'}",https://api.ebay.com/buy/browse/v1/item/v1%7C2...,"{'username': 'ticktock1-2-3', 'feedbackPercent...",Used,3000,...,EBAY_US,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,v1|266544978871|0,Zoo Med Aquatic Turtle Maintenance Food Select...,[1285],"[{'categoryId': '1285', 'categoryName': 'Repti...",{'imageUrl': 'https://i.ebayimg.com/images/g/-...,"{'value': '23.99', 'currency': 'USD'}",https://api.ebay.com/buy/browse/v1/item/v1%7C2...,"{'username': 'kens_fish', 'feedbackPercentage'...",New,1000,...,EBAY_US,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
996,v1|277873278365|2560805379958,Brine Shrimp Meal Fine 0.2mm Artemia Powder F...,[20759],"[{'categoryId': '20759', 'categoryName': 'Food...",{'imageUrl': 'https://i.ebayimg.com/images/g/a...,"{'value': '7.98', 'currency': 'USD'}",https://api.ebay.com/buy/browse/v1/item/v1%7C2...,"{'username': 'glossofactory', 'feedbackPercent...",New,1000,...,EBAY_US,"{'originalPrice': {'value': '9.98', 'currency'...",https://api.ebay.com/buy/browse/v1/item/get_it...,SELLER_DEFINED_VARIATIONS,NaN,NaN,NaN,NaN,NaN,NaN
997,v1|167809404968|0,500–1000+ Live Daphnia Magna | Freshwater Fish...,[20759],"[{'categoryId': '20759', 'categoryName': 'Food...",{'imageUrl': 'https://i.ebayimg.com/images/g/u...,"{'value': '29.99', 'currency': 'USD'}",https://api.ebay.com/buy/browse/v1/item/v1%7C1...,"{'username': 'arcisaquarium', 'feedbackPercent...",New,1000,...,EBAY_US,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
998,v1|116477232132|0,Legendary Foods Protein Pastry - Strawberry 12...,[1278],"[{'categoryId': '1278', 'categoryName': 'Endur...",{'imageUrl': 'https://i.ebayimg.com/images/g/M...,"{'value': '18.65', 'currency': 'USD'}",https://api.ebay.com/buy/browse/v1/item/v1%7C1...,"{'username': 'innocent_librastar', 'feedbackPe...",New,1000,...,EBAY_US,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
999,v1|147355470575|0,Pumpkin Seeds Pepitas Raw Hulled 4LB Bulk Unsa...,[257952],"[{'categoryId': '257952', 'categoryName': 'Nut...",{'imageUrl': 'https://i.ebayimg.com/images/g/Y...,"{'value': '28.00', 'currency': 'USD'}",https://api.ebay.com/buy/browse/v1/item/v1%7C1...,"{'username': 'perez-256534', 'feedbackPercenta...",New,1000,...,EBAY_US,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
# process of data cleaning (sliver)
df_updated1=df_all.rename(columns={'itemId':'ProductId'})
df_updated2=df_updated1.rename(columns={'title': 'Product'})
df_updated3=df_updated2.rename(columns={'leafCategoryIds':'CategoryId'})
df_updated4=df_updated3.rename(columns={'itemWebUrl':'productWebUrl'})
df_updated5=df_updated4.rename(columns={'legacyItemId':'legacyProductId'})
df_updated6=df_updated5.rename(columns={'itemOriginDate':'productOriginDate'})
df_updated=df_updated6.rename(columns={'itemCreationDate':'productCreationDate'})
#itemOriginDate
df_updated


df_updated['productOriginDate']= pd.to_datetime(df_updated['productOriginDate'])
df_updated['productCreationDate']= pd.to_datetime(df_updated['productCreationDate'])






x = []
cu = []

for i in df_updated['price']:
    if isinstance(i, dict):
        x.append(float(i.get('value', 0)))
        cu.append(i.get('currency', 'Unknown'))
    else:
        x.append(float(i))
        cu.append('Unknown')


df_updated['price']=x
df_updated['currency']=cu
df_updated=df_updated.drop('itemGroupHref',axis=1)
df_updated=df_updated.drop('itemHref',axis=1)
df_updated=df_updated.drop('itemGroupType',axis=1)
df_updated=df_updated.drop('additionalImages',axis=1)
df_updated


df_updated['marketingPrice'] = df_updated['marketingPrice'].fillna("Unknown")
df_updated['pickupOptions']=df_updated['pickupOptions'].fillna("Unknown")
df_updated['epid']=df_updated['epid'].fillna("Unknown")
df_updated['priceDisplayCondition']=df_updated['priceDisplayCondition'].fillna("Unknown")
if 'bidCount' in df_updated.columns and 'currentBidPrice' in df_updated.columns and 'itemEndDate' in df_updated.columns:
    df_updated['bidCount'] = df_updated['bidCount'].fillna("Unknown")
    df_updated['currentBidPrice'] = df_updated['currentBidPrice'].fillna("Unknown")
    df_updated['itemEndDate']=df_updated['itemEndDate'].fillna("Unknown")
df_updated['image']=df_updated['image'].fillna("Unknown")
df_updated['categories']=df_updated['categories'].fillna("Unknown")
df_updated['condition']=df_updated['condition'].fillna("Unknown")
df_updated['shippingOptions']=df_updated['shippingOptions'].fillna("Unknown")
z=[]
m=[]
for i in df_updated['image']:
   if 'imageUrl' in i:
      m.append(i['imageUrl'])
   else:
      m.append("Unknown")
      


df_updated['image']=m
df_updated=df_updated.drop('thumbnailImages',axis=1)
a=[]

#for i in df_updated['categories']:
 #  b=i[0]
  # a.append(b['categoryName'])

#df_updated['categories']=a
#df_updated


s=[]
sc1=[]
for i in df_updated['shippingOptions']:
   sc=i[0]
  
   if 'shippingCostType' in sc:
      s.append(sc['shippingCostType'].title())
   else:
      s.append('Unknown')
   

df_updated['shippingCostType']=s
for i in df_updated['shippingOptions']:
   sc=i[0]
   if 'shippingCost' in sc:
      if sc['shippingCost']['value']=='0.00':
         sc1.append(0.00)
      elif sc['shippingCost']['value']!='0.00':
         sc1.append(f'{float(sc['shippingCost']['value'])}')
   else:
      sc1.append(0.00)

sc2=[]
for i in df_updated['shippingOptions']:
   sc=i[0]
   if 'minEstimatedDeliveryDate' in sc:
      sc2.append(pd.to_datetime(sc['minEstimatedDeliveryDate']))
   else:
      sc2.append(0-0-0)

sc3=[]
for i in df_updated['shippingOptions']:
   sc=i[0]
   if 'maxEstimatedDeliveryDate' in sc:
      sc3.append(pd.to_datetime(sc['maxEstimatedDeliveryDate']))
   else:
      sc3.append(0-0-0)

co=[]
for i in df_updated['itemLocation']:
   if 'country' in i:
      co.append(i['country'])
   else:
      co.append("Unknown")

pc=[]
for i in df_updated['itemLocation']:
   if 'postalCode' in i:
      pc.append(i['postalCode'])
   else:
      pc.append("Unknown")

fx=[]
for i in df_updated['buyingOptions']:
   if len(i) == 2:
      fx.append("Fixed Price and Best Offer")
   else:
      fx.append("Fixed Price")

pk=[]
for i in df_updated['pickupOptions']:
   d=i[0]
   if 'pickupLocationType' in i[0]:
      pk.append(d['pickupLocationType'].title())
   else:
      pk.append("Unknown")

ori=[]
for i in df_updated['marketingPrice']:
  if 'originalPrice' in i:
     ori.append(float(i['originalPrice']['value']))
  else:
     ori.append(0.00)

disp=[]
for i in df_updated['marketingPrice']:
  if 'discountPercentage' in i:
     disp.append(int(i['discountPercentage']))
  else:
     disp.append(0)


disa=[]
for i in df_updated['marketingPrice']:
  if 'discountAmount' in i:
     disa.append(float(i['discountAmount']['value']))
  else:
     disa.append(0.00)

df_updated['originalPrice']=ori
df_updated['discountPercentage']=disp
df_updated['discountAmount']=disa



cat=[]
idc=[]
for i in df_updated['categories']:
   b=i[0]
   cat.append(b['categoryName'])



for i in df_updated['CategoryId']:
   idc.append(int(i[0]))

df_updated['CategoryId']=idc

df_updated['categories']=cat
df_updated['shippingCost']=sc1
df_updated['minEstimatedDeliveryDate']=sc2
df_updated['maxEstimatedDeliveryDate']=sc3
df_updated['Country']=co
df_updated['PostalCode']=pc
df_updated['buyingOptions']=fx
df_updated['pickupOptions']=pk
df_updated=df_updated.drop('shippingOptions',axis=1)
df_updated=df_updated.drop('itemLocation',axis=1)
df_updated=df_updated.drop('marketingPrice',axis=1)
df_updated=df_updated.drop('legacyProductId',axis=1)
df_updated=df_updated.drop('priorityListing',axis=1)
if 'bidCount' in df_updated.columns:
   df_updated=df_updated.drop('bidCount',axis=1)
df_updated=df_updated.drop('epid',axis=1)


se=[]
fp=[]
fs=[]
for i in df_updated['seller']:
   if 'username' in i:
      se.append(i['username'])
   else:
      se.append('Unknown User')
   

for i in df_updated['seller']:
   if 'feedbackPercentage' in i:
      fp.append(float(i['feedbackPercentage']))
   else:
      fp.append(0.0)

for i in df_updated['seller']:
   if 'feedbackScore' in i:
      fs.append(int(i['feedbackScore']))
   else:
      fs.append(0)

df_updated['seller']=se
df_updated['feedbackPrecentage']=fp
df_updated['feedbackScore']=fs

df_updated['ProductId'] = df_updated['ProductId'].str.split('|').str[1]
df_updated['ProductId'] = df_updated['ProductId'].astype(int)
df_updated
cb=[]
if 'currentBidPrice' in df_updated.columns:
   for i in df_updated['currentBidPrice']:
    if 'value' in i:
     cb.append(float(i['value']))
    elif 'Unknown'in i:
      cb.append(0)

if 'currentBidPrice' in df_updated.columns:
   df_updated['currentBidPrice']=cb

if 'itemEndDate' in df_updated.columns:
   df_updated=df_updated.drop('itemEndDate',axis=1)

In [6]:
df_updated['conditionId']=df_updated['conditionId'].fillna(404)

In [7]:
df_updated

,ProductId,Product,CategoryId,categories,image,price,seller,condition,conditionId,buyingOptions,...,originalPrice,discountPercentage,discountAmount,shippingCost,minEstimatedDeliveryDate,maxEstimatedDeliveryDate,Country,PostalCode,feedbackPrecentage,feedbackScore
0,256245941032,"Dell Latitude 3190 Laptop 11.6"" Intel Celeron ...",177,PC Laptops & Netbooks,https://i.ebayimg.com/images/g/US4AAeSwXbZqF78...,119.25,discountcomputerdepot,Good - Refurbished,2030,Fixed Price,...,0.00,0,0.00,0.0,2026-06-11 07:00:00+00:00,2026-06-13 07:00:00+00:00,US,757**,99.5,163185
1,254078693996,"HP ProBook Touchscreen Laptop 11.6"" Core i3 8G...",177,PC Laptops & Netbooks,https://i.ebayimg.com/images/g/ebMAAeSwQ6RpumD...,149.07,discountcomputerdepot,Good - Refurbished,2030,Fixed Price,...,0.00,0,0.00,0.0,2026-06-11 07:00:00+00:00,2026-06-13 07:00:00+00:00,US,757**,99.5,163185
2,116841881853,EXECUTIVE SPECIAL~ 15.6 DELL Latitude Laptop: ...,177,PC Laptops & Netbooks,https://i.ebayimg.com/images/g/3IoAAeSwey5qKBR...,409.95,regadget,Excellent - Refurbished,2010,Fixed Price and Best Offer,...,0.00,0,0.00,0.0,2026-06-11 07:00:00+00:00,2026-06-11 07:00:00+00:00,US,410**,99.7,13374
3,254654754368,"Dell Latitude Touchscreen Laptop 11.6"" Pentium...",177,PC Laptops & Netbooks,https://i.ebayimg.com/images/g/gU4AAeSw~DRpOpe...,150.91,discountcomputerdepot,Good - Refurbished,2030,Fixed Price and Best Offer,...,795.00,81,644.09,0.0,2026-06-11 07:00:00+00:00,2026-06-13 07:00:00+00:00,US,757**,99.5,163185
4,235711075450,"Windows 11 PRO Laptop Notebook PC Computer, 8G...",177,PC Laptops & Netbooks,https://i.ebayimg.com/images/g/KMMAAOSwJlFmyVx...,122.00,ticktock1-2-3,Used,3000,Fixed Price and Best Offer,...,0.00,0,0.00,0.0,2026-06-12 07:00:00+00:00,2026-06-17 07:00:00+00:00,US,754**,98.3,58947
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,266544978871,Zoo Med Aquatic Turtle Maintenance Food Select...,1285,Reptile Supplies,https://i.ebayimg.com/images/g/-xEAAeSwVXNqJ4G...,23.99,kens_fish,New,1000,Fixed Price,...,0.00,0,0.00,0.0,2026-06-11 07:00:00+00:00,2026-06-13 07:00:00+00:00,US,027**,99.8,42432
996,277873278365,Brine Shrimp Meal Fine 0.2mm Artemia Powder F...,20759,Food,https://i.ebayimg.com/images/g/aX0AAeSw8ZZp1WQ...,7.98,glossofactory,New,1000,Fixed Price,...,9.98,20,2.00,0.0,2026-06-11 07:00:00+00:00,2026-06-13 07:00:00+00:00,US,852**,100.0,5453
997,167809404968,500–1000+ Live Daphnia Magna | Freshwater Fish...,20759,Food,https://i.ebayimg.com/images/g/ufAAAeSwI8pp3O6...,29.99,arcisaquarium,New,1000,Fixed Price,...,0.00,0,0.00,0.0,2026-06-11 07:00:00+00:00,2026-06-13 07:00:00+00:00,US,327**,100.0,58
998,116477232132,Legendary Foods Protein Pastry - Strawberry 12...,1278,"Endurance & Energy Bars, Drinks & Pills",https://i.ebayimg.com/images/g/MDkAAOSwxBlnrTA...,18.65,innocent_librastar,New,1000,Fixed Price and Best Offer,...,0.00,0,0.00,0.0,2026-06-15 07:00:00+00:00,2026-06-18 07:00:00+00:00,US,100**,98.7,3036
999,147355470575,Pumpkin Seeds Pepitas Raw Hulled 4LB Bulk Unsa...,257952,Nuts & Seeds,https://i.ebayimg.com/images/g/YIoAAeSwXr5pawX...,28.00,perez-256534,New,1000,Fixed Price,...,0.00,0,0.00,0.0,2026-06-13 07:00:00+00:00,2026-06-20 07:00:00+00:00,US,917**,99.5,436

In [8]:
Product_Dim=df_updated.loc[:,['ProductId','Product','image','adultOnly','buyingOptions','availableCoupons','productWebUrl']]
Product_Dim

,ProductId,Product,image,adultOnly,buyingOptions,availableCoupons,productWebUrl
0,256245941032,"Dell Latitude 3190 Laptop 11.6"" Intel Celeron ...",https://i.ebayimg.com/images/g/US4AAeSwXbZqF78...,False,Fixed Price,False,https://www.ebay.com/itm/256245941032?_skw=Lap...
1,254078693996,"HP ProBook Touchscreen Laptop 11.6"" Core i3 8G...",https://i.ebayimg.com/images/g/ebMAAeSwQ6RpumD...,False,Fixed Price,False,https://www.ebay.com/itm/254078693996?_skw=Lap...
2,116841881853,EXECUTIVE SPECIAL~ 15.6 DELL Latitude Laptop: ...,https://i.ebayimg.com/images/g/3IoAAeSwey5qKBR...,False,Fixed Price and Best Offer,False,https://www.ebay.com/itm/116841881853?_skw=Lap...
3,254654754368,"Dell Latitude Touchscreen Laptop 11.6"" Pentium...",https://i.ebayimg.com/images/g/gU4AAeSw~DRpOpe...,False,Fixed Price and Best Offer,False,https://www.ebay.com/itm/254654754368?_skw=Lap...
4,235711075450,"Windows 11 PRO Laptop Notebook PC Computer, 8G...",https://i.ebayimg.com/images/g/KMMAAOSwJlFmyVx...,False,Fixed Price and Best Offer,False,https://www.ebay.com/itm/235711075450?_skw=Lap...
...,...,...,...,...,...,...,...
995,266544978871,Zoo Med Aquatic Turtle Maintenance Food Select...,https://i.ebayimg.com/images/g/-xEAAeSwVXNqJ4G...,False,Fixed Price,False,https://www.ebay.com/itm/266544978871?_skw=Foo...
996,277873278365,Brine Shrimp Meal Fine 0.2mm Artemia Powder F...,https://i.ebayimg.com/images/g/aX0AAeSw8ZZp1WQ...,False,Fixed Price,False,https://www.ebay.com/itm/277873278365?_skw=Foo...
997,167809404968,500–1000+ Live Daphnia Magna | Freshwater Fish...,https://i.ebayimg.com/images/g/ufAAAeSwI8pp3O6...,False,Fixed Price,False,https://www.ebay.com/itm/167809404968?_skw=Foo...
998,116477232132,Legendary Foods Protein Pastry - Strawberry 12...,https://i.ebayimg.com/images/g/MDkAAOSwxBlnrTA...,False,Fixed Price and Best Offer,False,https://www.ebay.com/itm/116477232132?_skw=Foo...
999,147355470575,Pumpkin Seeds Pepitas Raw Hulled 4LB Bulk Unsa...,https://i.ebayimg.com/images/g/YIoAAeSwXr5pawX...,False,Fixed Price,False,https://www.ebay.com/itm/147355470575?_skw=Foo...

In [9]:
Location_Dim=df_updated.loc[:,['Country','PostalCode']]
Location_Dim

    Country PostalCode
0        US      757**
1        US      757**
2        US      410**
3        US      757**
4        US      754**
..      ...        ...
995      US      027**
996      US      852**
997      US      327**
998      US      100**
999      US      917**

[1000 rows x 2 columns]

In [10]:
Category_Dim=df_updated.loc[:,['CategoryId','categories']]
Category_Dim

     CategoryId                               categories
0           177                    PC Laptops & Netbooks
1           177                    PC Laptops & Netbooks
2           177                    PC Laptops & Netbooks
3           177                    PC Laptops & Netbooks
4           177                    PC Laptops & Netbooks
..          ...                                      ...
995        1285                         Reptile Supplies
996       20759                                     Food
997       20759                                     Food
998        1278  Endurance & Energy Bars, Drinks & Pills
999      257952                             Nuts & Seeds

[1000 rows x 2 columns]

In [11]:
Condition_Dim=df_updated.loc[:,['conditionId','condition','priceDisplayCondition']]
Condition_Dim

    conditionId                condition priceDisplayCondition
0          2030       Good - Refurbished               Unknown
1          2030       Good - Refurbished               Unknown
2          2010  Excellent - Refurbished               Unknown
3          2030       Good - Refurbished               Unknown
4          3000                     Used               Unknown
..          ...                      ...                   ...
995        1000                      New               Unknown
996        1000                      New               Unknown
997        1000                      New               Unknown
998        1000                      New               Unknown
999        1000                      New               Unknown

[1000 rows x 3 columns]

In [12]:
Seller_Dim=df_updated.loc[:,['seller','feedbackPrecentage','feedbackScore']]
Seller_Dim

                    seller  feedbackPrecentage  feedbackScore
0    discountcomputerdepot                99.5         163185
1    discountcomputerdepot                99.5         163185
2                 regadget                99.7          13374
3    discountcomputerdepot                99.5         163185
4            ticktock1-2-3                98.3          58947
..                     ...                 ...            ...
995              kens_fish                99.8          42432
996          glossofactory               100.0           5453
997          arcisaquarium               100.0             58
998     innocent_librastar                98.7           3036
999           perez-256534                99.5            436

[1000 rows x 3 columns]

In [13]:
Seller_Dim = Seller_Dim.drop_duplicates(subset=['seller'])
Product_Dim = Product_Dim.drop_duplicates(subset=['ProductId'])
Condition_Dim = Condition_Dim.drop_duplicates(subset=['conditionId'])
Category_Dim = Category_Dim.drop_duplicates(subset=['CategoryId'])
Location_Dim=Location_Dim.drop_duplicates(subset=['Country'])

In [14]:
Location_Dim

    Country PostalCode
0        US      757**
523      BA      *****
549      TR    Unknown
613      BR    Unknown
618      CN    Unknown
694      AU       3***
702      PK    Unknown
779      KR    Unknown
818      TH    Unknown
853      AE    Unknown
953      CA     L4Y***

In [15]:
Condition_Dim

    conditionId                 condition priceDisplayCondition
0          2030        Good - Refurbished               Unknown
2          2010   Excellent - Refurbished               Unknown
4          3000                      Used               Unknown
6          1500                  Open box               Unknown
13         1000                       New               Unknown
17         2000   Certified - Refurbished               Unknown
27         2020   Very Good - Refurbished               Unknown
240        7000  For parts or not working               Unknown
530         404                   Unknown               Unknown
635        4000                 Very Good               Unknown
669        2750                  Like New               Unknown
886        5000                      Good               Unknown

In [16]:
dates = pd.concat([df_updated['productCreationDate'],df_updated['productOriginDate'],df_updated['minEstimatedDeliveryDate'],df_updated['maxEstimatedDeliveryDate']])
dates = pd.to_datetime(dates, utc=True).dt.tz_localize(None)
DimDate=pd.DataFrame()
DimDate['FullDate']=dates
DimDate['Day']=DimDate['FullDate'].dt.day
DimDate['Month']=DimDate['FullDate'].dt.month
DimDate['Year']=DimDate['FullDate'].dt.year
DimDate['Hour']=DimDate['FullDate'].dt.hour
DimDate['Minute']=DimDate['FullDate'].dt.minute
DimDate['Second']=DimDate['FullDate'].dt.second
DimDate['MonthName']=DimDate['FullDate'].dt.month_name()
DimDate

               FullDate  Day  Month  Year  Hour  Minute  Second MonthName
0   2023-10-06 14:32:43    6     10  2023    14      32      43   October
1   2019-01-17 22:02:26   17      1  2019    22       2      26   January
2   2025-10-23 16:58:50   23     10  2025    16      58      50   October
3   2020-07-15 20:38:38   15      7  2020    20      38      38      July
4   2024-08-24 04:12:00   24      8  2024     4      12       0    August
..                  ...  ...    ...   ...   ...     ...     ...       ...
995 2026-06-13 07:00:00   13      6  2026     7       0       0      June
996 2026-06-13 07:00:00   13      6  2026     7       0       0      June
997 2026-06-13 07:00:00   13      6  2026     7       0       0      June
998 2026-06-18 07:00:00   18      6  2026     7       0       0      June
999 2026-06-20 07:00:00   20      6  2026     7       0       0      June

[4000 rows x 8 columns]

In [17]:
if 'currentBidPrice' in df_updated.columns:
    Fact_Table=df_updated.loc[:,['ProductId','CategoryId','price','conditionId','originalPrice','discountPercentage','discountAmount','shippingCost','feedbackPrecentage','feedbackScore','currentBidPrice','productCreationDate','productOriginDate','minEstimatedDeliveryDate','maxEstimatedDeliveryDate','seller','Country']]

else:
    Fact_Table=df_updated.loc[:,['ProductId','CategoryId','price','conditionId','originalPrice','discountPercentage','discountAmount','shippingCost','feedbackPrecentage','feedbackScore','productCreationDate','productOriginDate','minEstimatedDeliveryDate','maxEstimatedDeliveryDate','seller','Country']]

Fact_Table
Fact_Table['productCreationDate'] = Fact_Table['productCreationDate'].dt.date
Fact_Table['productOriginDate'] = Fact_Table['productOriginDate'].dt.date

In [18]:
Fact_Table['minEstimatedDeliveryDate'] = pd.to_datetime(
    Fact_Table['minEstimatedDeliveryDate'], errors='coerce', utc=True
)
Fact_Table['maxEstimatedDeliveryDate'] = pd.to_datetime(
    Fact_Table['maxEstimatedDeliveryDate'], errors='coerce', utc=True
)
Fact_Table['minEstimatedDeliveryDate'] = Fact_Table['minEstimatedDeliveryDate'].dt.date
Fact_Table['maxEstimatedDeliveryDate'] = Fact_Table['maxEstimatedDeliveryDate'].dt.date

In [19]:
import mysql.connector
from sqlalchemy import create_engine

conn = mysql.connector.connect(
  host="localhost",
  user="root",
  password=""
)
cursor = conn.cursor()
cursor.execute("CREATE DATABASE IF NOT EXISTS depi")
cursor.execute("USE depi")
cursor.execute('''
CREATE TABLE IF NOT EXISTS DimDate (
    DateId INT AUTO_INCREMENT PRIMARY KEY,
    FullDate Date,
    Day int,
  Month INT,
               Year INT,
               Hour INT,
               Minute INT,
               Second INT,
               MonthName VARCHAR(100)
)
''')
user = "root"
password = ""
host = "localhost"
database = "depi"
engine = create_engine(f"mysql+mysqlconnector://{user}:{password}@{host}/{database}")
DimDate.to_sql(
    name='DimDate',   # Table name in MySQL
    con=engine,        # Connection engine
    if_exists='append',  # 'replace' = overwrite table, 'append' = add rows
    index=False        # Do not write DataFrame index as a column
)



conn.commit()

ProgrammingError: 1045 (28000): Access denied for user 'root'@'localhost' (using password: NO)

In [150]:
cursor.execute("USE depi")
cursor.execute('''
CREATE TABLE IF NOT EXISTS DimLocation (
    LocationId INT AUTO_INCREMENT PRIMARY KEY,
    Country TEXT,
    PostalCode TEXT
)
''')

Location_Dim.to_sql(
    name='DimLocation',   # Table name in MySQL
    con=engine,        # Connection engine
    if_exists='append',  # 'replace' = overwrite table, 'append' = add rows
    index=False        # Do not write DataFrame index as a column
)

C:\Users\Ahmed\AppData\Local\Temp\ipykernel_29344\3652211004.py:10: UserWarning: The provided table name 'DimLocation' is not found exactly as such in the database after writing the table, possibly due to case sensitivity issues. Consider using lower case table names.
  Location_Dim.to_sql(

34

In [151]:
Location_Dim.to_sql(
    name='DimLocation',   # Table name in MySQL
    con=engine,        # Connection engine
    if_exists='append',  # 'replace' = overwrite table, 'append' = add rows
    index=False        # Do not write DataFrame index as a column
)
Location_Dim_mysql = pd.read_sql("SELECT * FROM DimLocation", con=engine)

location_map = dict(zip(Location_Dim_mysql['Country'], Location_Dim_mysql['LocationId']))

Fact_Table['LocationId'] = Fact_Table['Country'].map(location_map)

C:\Users\Ahmed\AppData\Local\Temp\ipykernel_29344\1171842953.py:1: UserWarning: The provided table name 'DimLocation' is not found exactly as such in the database after writing the table, possibly due to case sensitivity issues. Consider using lower case table names.
  Location_Dim.to_sql(

In [152]:
DimDate.to_sql(
    name='DimDate',
    con=engine,
    if_exists='append',
    index=False
)

# Fetch the table back with DateId
DimDate_mysql = pd.read_sql("SELECT * FROM DimDate", con=engine)

# Now you have DateId for mapping
date_id_map = dict(zip(DimDate_mysql['FullDate'], DimDate_mysql['DateId']))

# Map to fact table
Fact_Table['ProductCreationDateId'] = Fact_Table['productCreationDate'].map(date_id_map)
Fact_Table['ProductOriginDateId'] = Fact_Table['productOriginDate'].map(date_id_map)
Fact_Table['minEstimatedDeliveryDateId'] = Fact_Table['minEstimatedDeliveryDate'].map(date_id_map)
Fact_Table['maxEstimatedDeliveryDateId'] = Fact_Table['maxEstimatedDeliveryDate'].map(date_id_map)

C:\Users\Ahmed\AppData\Local\Temp\ipykernel_29344\2411967019.py:1: UserWarning: The provided table name 'DimDate' is not found exactly as such in the database after writing the table, possibly due to case sensitivity issues. Consider using lower case table names.
  DimDate.to_sql(

In [153]:
cursor.execute("USE depi")
cursor.execute('''
CREATE TABLE IF NOT EXISTS DimSeller (
    SellerId INT AUTO_INCREMENT PRIMARY KEY,
    Seller VARCHAR(200),
    Country VARCHAR(200),
  PostalCode VARCHAR(100),
               FeedbackPrecentage FLOAT,
               FeedbackScore INT
)
''')
Seller_Dim.to_sql(
    name='DimSeller',   # Table name in MySQL
    con=engine,        # Connection engine
    if_exists='append',  # 'replace' = overwrite table, 'append' = add rows
    index=False        # Do not write DataFrame index as a column
)

C:\Users\Ahmed\AppData\Local\Temp\ipykernel_29344\935089593.py:12: UserWarning: The provided table name 'DimSeller' is not found exactly as such in the database after writing the table, possibly due to case sensitivity issues. Consider using lower case table names.
  Seller_Dim.to_sql(

3059

In [154]:
Seller_Dim.to_sql(
    name='DimSeller',
    con=engine,
    if_exists='append',
    index=False
)

Seller_Dim_mysql = pd.read_sql("SELECT * FROM DimSeller", con=engine)

seller_map = dict(zip(Seller_Dim_mysql['Seller'], Seller_Dim_mysql['SellerId']))

Fact_Table['SellerId'] = Fact_Table['seller'].map(seller_map)

C:\Users\Ahmed\AppData\Local\Temp\ipykernel_29344\1220439700.py:1: UserWarning: The provided table name 'DimSeller' is not found exactly as such in the database after writing the table, possibly due to case sensitivity issues. Consider using lower case table names.
  Seller_Dim.to_sql(

In [155]:
Fact_Table
Fact_Table=Fact_Table.drop('productCreationDate',axis=1)
Fact_Table=Fact_Table.drop('productOriginDate',axis=1)
Fact_Table=Fact_Table.drop('maxEstimatedDeliveryDate',axis=1)
Fact_Table=Fact_Table.drop('minEstimatedDeliveryDate',axis=1)
Fact_Table=Fact_Table.drop('seller',axis=1)
Fact_Table=Fact_Table.drop('Country',axis=1)

In [71]:
!pip install mysql-connector-python

Requirement already satisfied: mysql-connector-python in c:\users\ahmed\anaconda3\lib\site-packages (9.6.0)

In [156]:
cursor.execute("USE depi")
cursor.execute('''
CREATE TABLE IF NOT EXISTS DimProduct (
    ProductId BIGINT PRIMARY KEY,
    Product TEXT,
    Image TEXT,
  AdultOnly BOOLEAN,
               BuyingOptions varchar(500),
               AvailableCoupons BOOLEAN,
               ProductWebURL TEXT
)
''')

In [157]:
Product_Dim.to_sql(
    name='DimProduct',   # Table name in MySQL
    con=engine,        # Connection engine
    if_exists='append',  # 'replace' = overwrite table, 'append' = add rows
    index=False        # Do not write DataFrame index as a column
)

C:\Users\Ahmed\AppData\Local\Temp\ipykernel_29344\1910535861.py:1: UserWarning: The provided table name 'DimProduct' is not found exactly as such in the database after writing the table, possibly due to case sensitivity issues. Consider using lower case table names.
  Product_Dim.to_sql(

6944

In [158]:

cursor.execute("USE depi")
cursor.execute('''
CREATE TABLE IF NOT EXISTS DimCondition (
     ConditionId BIGINT PRIMARY KEY,
    ConditionType TEXT,
    priceDisplayCondition TEXT
)
''')

In [159]:
Condition_Dim.rename(columns={'condition': 'conditionType'}, inplace=True)
Condition_Dim.to_sql(
    name='DimCondition',   # Table name in MySQL
    con=engine,        # Connection engine
    if_exists='append',  # 'replace' = overwrite table, 'append' = add rows
    index=False        # Do not write DataFrame index as a column
)

C:\Users\Ahmed\AppData\Local\Temp\ipykernel_29344\4260801231.py:2: UserWarning: The provided table name 'DimCondition' is not found exactly as such in the database after writing the table, possibly due to case sensitivity issues. Consider using lower case table names.
  Condition_Dim.to_sql(

12

In [160]:

cursor.execute("USE depi")
cursor.execute('''
CREATE TABLE IF NOT EXISTS DimCategory (
     CategoryId BIGINT PRIMARY KEY,
    Categories TEXT
    
)
''')

In [161]:
Category_Dim.to_sql(
    name='DimCategory',   # Table name in MySQL
    con=engine,        # Connection engine
    if_exists='append',  # 'replace' = overwrite table, 'append' = add rows
    index=False        # Do not write DataFrame index as a column
)

C:\Users\Ahmed\AppData\Local\Temp\ipykernel_29344\1743254496.py:1: UserWarning: The provided table name 'DimCategory' is not found exactly as such in the database after writing the table, possibly due to case sensitivity issues. Consider using lower case table names.
  Category_Dim.to_sql(

270

In [162]:
cursor.execute("USE depi") #minEstimatedDeliveryDateId
cursor.execute('''
CREATE TABLE IF NOT EXISTS FactTable (
               ProductCreationDateId INT,
    ProductOriginDateId INT,
    minEstimatedDeliveryDateId INT,
    maxEstimatedDeliveryDateId INT,
              
               ProductId BIGINT,
    CategoryId BIGINT,
    ConditionId BIGINT,
               SellerId INT,
               LocationId INT,
               FOREIGN KEY (LocationId) REFERENCES DimLocation(LocationId),
               FOREIGN KEY (SellerId) REFERENCES DimSeller(SellerId),
     FOREIGN KEY (ProductCreationDateId) REFERENCES DimDate(DateId),
               FOREIGN KEY (ProductOriginDateId) REFERENCES DimDate(DateId),
               FOREIGN KEY (ProductOriginDateId) REFERENCES DimDate(DateId),
               FOREIGN KEY (minEstimatedDeliveryDateId) REFERENCES DimDate(DateId),
               FOREIGN KEY (maxEstimatedDeliveryDateId) REFERENCES DimDate(DateId),
               FOREIGN KEY (ProductId) REFERENCES DimProduct(ProductId),
               FOREIGN KEY (CategoryId) REFERENCES DimCategory(CategoryId),
               Price FLOAT,
               FOREIGN KEY (ConditionId) REFERENCES DimCondition(ConditionId),
               OriginalPrice FLOAT,
               DiscountPercentage INT,
               DiscountAmount FLOAT,
               ShippingCost FLOAT,
               FeedbackPrecentage FLOAT,
               FeedbackScore INT,
               CurrentBidPrice FLOAT
               
)
''')

In [163]:
Fact_Table.to_sql(
    name='FactTable',   # Table name in MySQL
    con=engine,        # Connection engine
    if_exists='append',  # 'replace' = overwrite table, 'append' = add rows
    index=False        # Do not write DataFrame index as a column
)

C:\Users\Ahmed\AppData\Local\Temp\ipykernel_29344\3138578515.py:1: UserWarning: The provided table name 'FactTable' is not found exactly as such in the database after writing the table, possibly due to case sensitivity issues. Consider using lower case table names.
  Fact_Table.to_sql(

7600